unit unServerMethods;

interface

uses System.SysUtils, System.Classes, System.Json,
    Datasnap.DSServer, Datasnap.DSAuth, DataSnap.DSProviderDataModuleAdapter,
  FireDAC.Stan.Intf, FireDAC.Stan.Option, FireDAC.Stan.Error, FireDAC.UI.Intf,
  FireDAC.Phys.Intf, FireDAC.Stan.Def, FireDAC.Stan.Pool, FireDAC.Stan.Async,
  FireDAC.Phys, FireDAC.Phys.PG, FireDAC.Phys.PGDef, FireDAC.VCLUI.Wait,
  FireDAC.Comp.UI, Data.DB, FireDAC.Comp.Client, FireDAC.Stan.Param,
  FireDAC.DatS, FireDAC.DApt.Intf, FireDAC.DApt, Datasnap.Provider,
  FireDAC.Comp.DataSet;

type
  TServerMethods = class(TDSServerModule)
    conexao: TFDConnection;
    PgDriverLink: TFDPhysPgDriverLink;
    WaitCursor: TFDGUIxWaitCursor;
    qryAuditoria: TFDQuery;
    dspAuditoria: TDataSetProvider;
    qryBanco: TFDQuery;
    qryCargo: TFDQuery;
    qryCBO: TFDQuery;
    qryCEP: TFDQuery;
    qryCFOP: TFDQuery;
    qryCNAE: TFDQuery;
    qryControle: TFDQuery;
    dspBanco: TDataSetProvider;
    dspCargo: TDataSetProvider;
    dspCBO: TDataSetProvider;
    dspCEP: TDataSetProvider;
    dspCFOP: TDataSetProvider;
    dspCNAE: TDataSetProvider;
    dspControle: TDataSetProvider;
    qryCSTCOFINS: TFDQuery;
    dspCSTCOFINS: TDataSetProvider;
    qryCSTIPI: TFDQuery;
    dspCSTIPI: TDataSetProvider;
    qryCSTPIS: TFDQuery;
    qryDocumento: TFDQuery;
    qryECFCabecalho: TFDQuery;
    qryECFItem: TFDQuery;
    qryEmpresa: TFDQuery;
    qryEndereco: TFDQuery;
    qryEntradaCabecalho: TFDQuery;
    qryEntradaDuplicata: TFDQuery;
    qryEntradaItem: TFDQuery;
    qryEntradaItemImposto: TFDQuery;
    dspCSTPIS: TDataSetProvider;
    dspDocumento: TDataSetProvider;
    dspECFCabecalho: TDataSetProvider;
    dspECFItem: TDataSetProvider;
    dspEmpresa: TDataSetProvider;
    dspEndereco: TDataSetProvider;
    dspEntradaCabecalho: TDataSetProvider;
    dspEntradaDuplicata: TDataSetProvider;
    dspEntradaItem: TDataSetProvider;
    dspEntradaItemImposto: TDataSetProvider;
    qryEntradaLocalEntregaRetirada: TFDQuery;
    qryEntradaTransportadora: TFDQuery;
    qryEntradaTransportadoraReboque: TFDQuery;
    qryEstado: TFDQuery;
    qryEstoqueContagemCabecalho: TFDQuery;
    qryEstoqueCor: TFDQuery;
    qryEstoqueContagemDetalhe: TFDQuery;
    qryEstoqueGrade: TFDQuery;
    qryEstoqueTamanho: TFDQuery;
    qryHistoricoMovimento: TFDQuery;
    dspEntradaLocalEntregaRetirada: TDataSetProvider;
    dspEntradaTransportadora: TDataSetProvider;
    dspEntradaTransportadoraReboque: TDataSetProvider;
    dspEstado: TDataSetProvider;
    dspEstoqueContagemCabecalho: TDataSetProvider;
    dspEstoqueCor: TDataSetProvider;
    dspEstoqueContagemDetalhe: TDataSetProvider;
    dspEstoqueGrade: TDataSetProvider;
    dspEstoqueTamanho: TDataSetProvider;
    dspHistoricoMovimento: TDataSetProvider;
    qryIndicadorEconomico: TFDQuery;
    qryIndice: TFDQuery;
    qryLicitacao: TFDQuery;
    qryLicitacaoDocumento: TFDQuery;
    qryModelo: TFDQuery;
    qryMovimento: TFDQuery;
    qryMovimentoCheque: TFDQuery;
    qryMunicipio: TFDQuery;
    qryNCM: TFDQuery;
    qryNFeCabecalho: TFDQuery;
    dspIndicadorEconomico: TDataSetProvider;
    dspIndice: TDataSetProvider;
    dspLicitacao: TDataSetProvider;
    dspLicitacaoDocumento: TDataSetProvider;
    dspModelo: TDataSetProvider;
    dspMovimento: TDataSetProvider;
    dspMovimentoCheque: TDataSetProvider;
    dspMunicipio: TDataSetProvider;
    dspNCM: TDataSetProvider;
    dspNFeCabecalho: TDataSetProvider;
    qryNFeCupomFiscalReferenciado: TFDQuery;
    qryNFeDeclaracaoImportacao: TFDQuery;
    qryNFeDestinatario: TFDQuery;
    qryNFeDuplicata: TFDQuery;
    qryNFeImportacaoDetalhe: TFDQuery;
    qryNFeItem: TFDQuery;
    qryNFeItemII: TFDQuery;
    qryNFeItemImposto: TFDQuery;
    qryNFeLocalEntregaRetirada: TFDQuery;
    qryNFeNFReferenciada: TFDQuery;
    dspNFeCupomFiscalReferenciado: TDataSetProvider;
    dspNFeDeclaracaoImportacao: TDataSetProvider;
    dspNFeDestinatario: TDataSetProvider;
    dspNFeDuplicata: TDataSetProvider;
    dspNFeImportacaoDetalhe: TDataSetProvider;
    dspNFeItem: TDataSetProvider;
    dspNFeItemII: TDataSetProvider;
    dspNFeItemImposto: TDataSetProvider;
    dspNFeLocalEntregaRetirada: TDataSetProvider;
    dspNFeNFReferenciada: TDataSetProvider;
    qryNFeProdutorRuralReferenciada: TFDQuery;
    qryNFeReferenciada: TFDQuery;
    qryNFeTransportadora: TFDQuery;
    qryNFeTransportadoraReboque: TFDQuery;
    qryOrcamentoCabecalho: TFDQuery;
    qryOrcamentoItem: TFDQuery;
    qryPais: TFDQuery;
    qryPedidoCabecalho: TFDQuery;
    qryPedidoItem: TFDQuery;
    qryPessoa: TFDQuery;
    dspNFeProdutorRuralReferenciada: TDataSetProvider;
    dspNFeReferenciada: TDataSetProvider;
    dspNFeTransportadora: TDataSetProvider;
    dspNFeTransportadoraReboque: TDataSetProvider;
    dspOrcamentoCabecalho: TDataSetProvider;
    dspOrcamentoItem: TDataSetProvider;
    dspPais: TDataSetProvider;
    dspPedidoCabecalho: TDataSetProvider;
    dspPedidoItem: TDataSetProvider;
    dspPessoa: TDataSetProvider;
    qryPessoaCliente: TFDQuery;
    qryPessoaColaborador: TFDQuery;
    qryPessoaContador: TFDQuery;
    qryPessoaFornecedor: TFDQuery;
    qryPessoaRepresentante: TFDQuery;
    qryPessoaTransportadora: TFDQuery;
    qryPessoaVendedor: TFDQuery;
    qryPlanoContasFinanceiro: TFDQuery;
    qryPlanoContasGerencial: TFDQuery;
    qryPortador: TFDQuery;
    dspPessoaCliente: TDataSetProvider;
    dspPessoaColaborador: TDataSetProvider;
    dspPessoaContador: TDataSetProvider;
    dspPessoaFornecedor: TDataSetProvider;
    dspPessoaRepresentante: TDataSetProvider;
    dspPessoaTransportadora: TDataSetProvider;
    dspPessoaVendedor: TDataSetProvider;
    dspPlanoContasFinanceiro: TDataSetProvider;
    dspPlanoContasGerencial: TDataSetProvider;
    dspPortador: TDataSetProvider;
    qryPortadorHistorico: TFDQuery;
    qryProduto: TFDQuery;
    qryProdutoFornecedor: TFDQuery;
    qryProdutoGrupo: TFDQuery;
    qryProdutoPromocao: TFDQuery;
    qryProdutoSubGrupo: TFDQuery;
    qryProdutoTabelaPreco: TFDQuery;
    qryProdutoUnidade: TFDQuery;
    qryProdutoUnidadeConversao: TFDQuery;
    qryRegraFiscal: TFDQuery;
    dspPortadorHistorico: TDataSetProvider;
    dspProduto: TDataSetProvider;
    dspProdutoFornecedor: TDataSetProvider;
    dspProdutoGrupo: TDataSetProvider;
    dspProdutoPromocao: TDataSetProvider;
    dspProdutoSubGrupo: TDataSetProvider;
    dspProdutoTabelaPreco: TDataSetProvider;
    dspProdutoUnidade: TDataSetProvider;
    dspProdutoUnidadeConversao: TDataSetProvider;
    dspRegraFiscal: TDataSetProvider;
    qryRegraFiscalObservacao: TFDQuery;
    qrySerie: TFDQuery;
    qrySetor: TFDQuery;
    qryTelefone: TFDQuery;
    qryTipoOperacao: TFDQuery;
    qryTipoTelefone: TFDQuery;
    qryUnidadeNegocio: TFDQuery;
    dspRegraFiscalObservacao: TDataSetProvider;
    dspSerie: TDataSetProvider;
    dspSetor: TDataSetProvider;
    dspTelefone: TDataSetProvider;
    dspTipoOperacao: TDataSetProvider;
    dspTipoTelefone: TDataSetProvider;
    dspUnidadeNegocio: TDataSetProvider;
    qrySerieidserie: TIntegerField;
    qrySeriedescricao: TWideStringField;
    qrySerienumeracao: TIntegerField;
    qryBancoidbanco: TWideStringField;
    qryBanconome: TWideStringField;
    qryCFOPidcfop: TIntegerField;
    qryCFOPidtipooperacao: TIntegerField;
    qryCFOPcfop: TIntegerField;
    qryCFOPdescricao: TWideStringField;
    qryCFOPdescricaonf: TWideStringField;
    qryCFOPaplicacao: TWideMemoField;
    qryCFOPtipooperacaodescricao: TWideStringField;
    qryControleidcontrole: TIntegerField;
    qryControlesequencia: TSmallintField;
    qryControledescricao: TWideStringField;
    qryCSTCOFINSidcstcofins: TIntegerField;
    qryCSTCOFINSdescricao: TWideStringField;
    qryCSTCOFINSobservacao: TWideMemoField;
    qryCSTIPIidcstipi: TIntegerField;
    qryCSTIPIdescricao: TWideStringField;
    qryCSTIPIobservacao: TWideMemoField;
    qryCSTPISidcstpis: TIntegerField;
    qryCSTPISdescricao: TWideStringField;
    qryDocumentoiddocumento: TIntegerField;
    qryDocumentocaminho: TWideMemoField;
    qryDocumentoarquivo: TWideMemoField;
    qryECFItemidecfitem: TIntegerField;
    qryECFItemidproduto: TIntegerField;
    qryECFItemidecfcabecalho: TIntegerField;
    qryECFItemgtin: TWideStringField;
    qryECFItemserieecf: TWideStringField;
    qryECFItemquantidade: TFloatField;
    qryECFItemvalorunitario: TFloatField;
    qryECFItemvalortotal: TFloatField;
    qryECFItemtotalitem: TFloatField;
    qryECFItembaseicms: TFloatField;
    qryECFItemtaxaicms: TFloatField;
    qryECFItemvaloricms: TFloatField;
    qryECFItemtaxadesconto: TFloatField;
    qryECFItemvalordesconto: TFloatField;
    qryECFItemtaxaissqn: TFloatField;
    qryECFItemvalorissqn: TFloatField;
    qryECFItemtaxapis: TFloatField;
    qryECFItemvalorpis: TFloatField;
    qryECFItemtaxacofins: TFloatField;
    qryECFItemvalorcofiins: TFloatField;
    qryECFItemtaxaacrescimo: TFloatField;
    qryECFItemvaloracrescimo: TFloatField;
    qryECFItemtotalizadorparcial: TFloatField;
    qryECFItemcst: TSmallintField;
    qryECFItemcancelado: TBooleanField;
    qryECFItemmovimentaestoque: TBooleanField;
    qryECFItemecficmsst: TWideStringField;
    qryECFItemprodutodescricao: TWideMemoField;
    qryEmpresaidempresa: TIntegerField;
    qryEmpresarazaosocial: TWideStringField;
    qryEmpresanomefantasia: TWideStringField;
    qryEmpresahomepage: TWideStringField;
    qryEmpresaimagemlogotipo: TWideMemoField;
    qryEmpresatiporegime: TWideStringField;
    qryEnderecoidendereco: TIntegerField;
    qryEnderecoidpessoa: TIntegerField;
    qryEnderecoidecfcabecalho: TIntegerField;
    qryEnderecoidentradalocalentregaretirada: TIntegerField;
    qryEnderecoidentradatransportadora: TIntegerField;
    qryEnderecoidunidadedenegocio: TIntegerField;
    qryEnderecoidestado: TWideStringField;
    qryEnderecoidcep: TWideStringField;
    qryEnderecoidmunicipio: TIntegerField;
    qryEnderecologradouro: TWideStringField;
    qryEndereconumero: TWideStringField;
    qryEnderecocomplemento: TWideStringField;
    qryEnderecobairro: TWideStringField;
    qryEnderecoprincipal: TWideStringField;
    qryEnderecoentrega: TWideStringField;
    qryEnderecocobranca: TWideStringField;
    qryEnderecocorrespondencia: TWideStringField;
    qryEntradaDuplicataidentradaduplicata: TIntegerField;
    qryEntradaDuplicataidentradacabecalho: TIntegerField;
    qryEntradaDuplicatanumero: TWideStringField;
    qryEntradaDuplicatavalor: TFloatField;
    qryEntradaDuplicatadatavencimento: TDateField;
    qryEntradaItemidentradaitem: TIntegerField;
    qryEntradaItemidentradacabecalho: TIntegerField;
    qryEntradaItemidproduto: TIntegerField;
    qryEntradaItemnumeroitem: TIntegerField;
    qryEntradaItemcodigoproduto: TWideStringField;
    qryEntradaItemgtin: TWideStringField;
    qryEntradaItemdescricaoproduto: TWideStringField;
    qryEntradaItemncm: TIntegerField;
    qryEntradaItemextipi: TIntegerField;
    qryEntradaItemcfop: TIntegerField;
    qryEntradaItemunidadecomercial: TWideStringField;
    qryEntradaItemquantidadecomercial: TFloatField;
    qryEntradaItemvaloriunitariocomercial: TFloatField;
    qryEntradaItemvalorbrutoproduto: TFloatField;
    qryEntradaItemunidadetributavel: TWideStringField;
    qryEntradaItemquantidadetributavel: TFloatField;
    qryEntradaItemvalorunitariotributavel: TFloatField;
    qryEntradaItemvalorfrete: TFloatField;
    qryEntradaItemvalorseguro: TFloatField;
    qryEntradaItemvalordesconto: TFloatField;
    qryEntradaItemvaloroutrasdespesas: TFloatField;
    qryEntradaItementratotal: TBooleanField;
    qryEntradaItemvalorsubtotal: TFloatField;
    qryEntradaItemvalortotal: TFloatField;
    qryEntradaItemnumeropedido: TFloatField;
    qryEntradaItemitempedido: TFloatField;
    qryEntradaIteminformacoesadicionais: TWideMemoField;
    qryEntradaItemprodutodescricao: TWideMemoField;
    qryEntradaItemImpostoidentradaitemimposto: TIntegerField;
    qryEntradaItemImpostoidentradaitem: TIntegerField;
    qryEntradaItemImpostoorigemmercadoria: TSmallintField;
    qryEntradaItemImpostoicmscst: TSmallintField;
    qryEntradaItemImpostocsosn: TSmallintField;
    qryEntradaItemImpostoicmsmodalidadebc: TSmallintField;
    qryEntradaItemImpostoicmsreducaobc: TFloatField;
    qryEntradaItemImpostoicmsbasecalculo: TFloatField;
    qryEntradaItemImpostoicmsaliquota: TFloatField;
    qryEntradaItemImpostoicmsvalor: TFloatField;
    qryEntradaItemImpostoicmsmotivodesoneracao: TWideStringField;
    qryEntradaItemImpostoicmsmodalidadebcst: TSmallintField;
    qryEntradaItemImpostoicmsmvast: TFloatField;
    qryEntradaItemImpostoicmsreducaobcst: TFloatField;
    qryEntradaItemImpostoicmsvalorbcst: TFloatField;
    qryEntradaItemImpostoicmsaliquotast: TFloatField;
    qryEntradaItemImpostoicmsvalorst: TFloatField;
    qryEntradaItemImpostoicmsvalorbcstretido: TFloatField;
    qryEntradaItemImpostoicmsvalorstretido: TFloatField;
    qryEntradaItemImpostoicmsvalorbcstdestino: TFloatField;
    qryEntradaItemImpostoicmsvalorstdestino: TFloatField;
    qryEntradaItemImpostoicmsaliquotacreditosn: TFloatField;
    qryEntradaItemImpostoicmsvalorcreditosn: TFloatField;
    qryEntradaItemImpostoprecentualbcoperacaopropria: TFloatField;
    qryEntradaItemImpostoufst: TWideStringField;
    qryEntradaItemImpostoipienquadramento: TWideStringField;
    qryEntradaItemImpostoipicnpjprodutor: TWideStringField;
    qryEntradaItemImpostoipicst: TSmallintField;
    qryEntradaItemImpostoipivalorbc: TFloatField;
    qryEntradaItemImpostoipialiquota: TFloatField;
    qryEntradaItemImpostoipiquantidadeunidadetributavel: TFloatField;
    qryEntradaItemImpostoipivalorunidadetributavel: TFloatField;
    qryEntradaItemImpostoipivalor: TFloatField;
    qryEntradaItemImpostocofinscst: TSmallintField;
    qryEntradaItemImpostocofinsquantidadevendida: TFloatField;
    qryEntradaItemImpostocofinsbc: TFloatField;
    qryEntradaItemImpostocofinsaliquotapercentual: TFloatField;
    qryEntradaItemImpostocofinsaliquotavalor: TFloatField;
    qryEntradaItemImpostocofinsvalor: TFloatField;
    qryEntradaItemImpostopiscst: TSmallintField;
    qryEntradaItemImpostopisquantidadevalor: TFloatField;
    qryEntradaItemImpostopisbc: TFloatField;
    qryEntradaItemImpostopisaliquotapercentual: TFloatField;
    qryEntradaItemImpostopisaliquotavalor: TFloatField;
    qryEntradaItemImpostopisvalor: TFloatField;
    qryEntradaItemImpostoissbc: TFloatField;
    qryEntradaItemImpostoissaliquota: TFloatField;
    qryEntradaItemImpostoissvalor: TFloatField;
    qryEntradaItemImpostoissmunicipio: TIntegerField;
    qryEntradaItemImpostoissitemlistaservico: TIntegerField;
    qryEntradaItemImpostoisstributacao: TSmallintField;
    qryEntradaLocalEntregaRetiradaidentradalocalentregaretirada: TIntegerField;
    qryEntradaLocalEntregaRetiradaidentradacabecalho: TIntegerField;
    qryEntradaLocalEntregaRetiradacpf_cnpj: TWideStringField;
    qryEntradaLocalEntregaRetiradalogradouro: TWideStringField;
    qryEntradaLocalEntregaRetiradanumero: TWideStringField;
    qryEntradaLocalEntregaRetiradacomplemento: TWideStringField;
    qryEntradaLocalEntregaRetiradabairro: TWideStringField;
    qryEntradaLocalEntregaRetiradatipo: TWideStringField;
    qryEstoqueContagemCabecalhoidestoquecontagemcabecalho: TIntegerField;
    qryEstoqueContagemCabecalhoidempresa: TIntegerField;
    qryEstoqueContagemCabecalhodatacontagem: TDateField;
    qryEstoqueContagemCabecalhoestoqueatualizado: TWideStringField;
    qryEstoqueContagemCabecalhonomefantasia: TWideStringField;
    qryEstoqueCoridestoquecor: TIntegerField;
    qryEstoqueCorcodigo: TWideStringField;
    qryEstoqueCornome: TWideStringField;
    qryEstoqueGradeidestoquegrade: TIntegerField;
    qryEstoqueGradeidproduto: TIntegerField;
    qryEstoqueGradeidestoquecor: TIntegerField;
    qryEstoqueGradeidestoquetamanho: TIntegerField;
    qryEstoqueGradecodigo: TWideStringField;
    qryEstoqueGradequantidade: TFloatField;
    qryEstoqueGradeprodutonome: TWideStringField;
    qryEstoqueGradecornome: TWideStringField;
    qryEstoqueGradetamanhonome: TWideStringField;
    qryEstoqueTamanhoidestoquetamanho: TIntegerField;
    qryEstoqueTamanhocodigo: TWideStringField;
    qryEstoqueTamanhonome: TWideStringField;
    qryHistoricoMovimentoidhistoricomovimento: TIntegerField;
    qryHistoricoMovimentodescricao: TWideStringField;
    qryHistoricoMovimentotipo: TWideStringField;
    qryHistoricoMovimentocontaliquidacao: TIntegerField;
    qryHistoricoMovimentoativo: TBooleanField;
    qryCBOidcbo: TIntegerField;
    qryCBOcodigo2002: TWideStringField;
    qryCBOcodigo1994: TWideStringField;
    qryCBOnome: TWideStringField;
    qryCBOobservacao: TWideMemoField;
    qryCargoidcargo: TIntegerField;
    qryCargoidcbo: TIntegerField;
    qryCargonome: TWideStringField;
    qryCargodescricao: TWideMemoField;
    qryCargosalario: TFloatField;
    qryCargocbonome: TWideStringField;
    qryAuditoriaidauditoria: TIntegerField;
    qryAuditoriadataregistro: TDateField;
    qryAuditoriahoraregistro: TTimeField;
    qryAuditoriaacao: TWideStringField;
    qryAuditoriadescricao: TWideMemoField;
    qryAuditoriaidunidadenegocio: TIntegerField;
    qryAuditorianomefantasia: TWideStringField;
    qryCEPidcep: TWideStringField;
    qryCEPidmunicipio: TIntegerField;
    qryCEPlogradouro: TWideStringField;
    qryCEPcomplemento: TWideStringField;
    qryCEPbairro: TWideStringField;
    qryCEPmunicipionome: TWideStringField;
    qryCNAEidcnae: TIntegerField;
    qryCNAEcodigo: TIntegerField;
    qryCNAEdenominacao: TWideMemoField;
    qryECFCabecalhoidecfcabecalho: TIntegerField;
    qryECFCabecalhoidpessoa: TIntegerField;
    qryECFCabecalhonomecaixa: TWideStringField;
    qryECFCabecalhoserieecf: TWideStringField;
    qryECFCabecalhodatavenda: TDateField;
    qryECFCabecalhohoravenda: TTimeField;
    qryECFCabecalhovalorvenda: TFloatField;
    qryECFCabecalhotaxadesconto: TFloatField;
    qryECFCabecalhovalordesconto: TIntegerField;
    qryECFCabecalhotaxaacrescimo: TFloatField;
    qryECFCabecalhovaloracrescimo: TFloatField;
    qryECFCabecalhovalorfinal: TFloatField;
    qryECFCabecalhovalorrecebido: TFloatField;
    qryECFCabecalhotroco: TFloatField;
    qryECFCabecalhovalorcancelado: TFloatField;
    qryECFCabecalhototalprodutos: TFloatField;
    qryECFCabecalhototaldocumento: TFloatField;
    qryECFCabecalhobaseicms: TFloatField;
    qryECFCabecalhovaloricms: TFloatField;
    qryECFCabecalhoicmsoutras: TFloatField;
    qryECFCabecalhoissqn: TFloatField;
    qryECFCabecalhopis: TFloatField;
    qryECFCabecalhocofins: TFloatField;
    qryECFCabecalhoacrescimoitens: TFloatField;
    qryECFCabecalhodescontoitens: TFloatField;
    qryECFCabecalhostatusvenda: TWideStringField;
    qryECFCabecalhonomecliente: TWideStringField;
    qryECFCabecalhocpfcnpjcliente: TWideStringField;
    qryECFCabecalhocupomcancelado: TBooleanField;
    qryECFCabecalhoidunidadenegocio: TIntegerField;
    qryECFCabecalhonomefantasia: TWideStringField;
    qryECFCabecalhopessoanome: TWideStringField;
    qryEntradaCabecalhoidentradacabecalho: TIntegerField;
    qryEntradaCabecalhoserie: TWideStringField;
    qryEntradaCabecalhomodelo: TWideStringField;
    qryEntradaCabecalhoufemitente: TWideStringField;
    qryEntradaCabecalhocodigonumerico: TWideStringField;
    qryEntradaCabecalhonaturezaoperacao: TIntegerField;
    qryEntradaCabecalhoindicadorformapagamento: TBooleanField;
    qryEntradaCabecalhonumero: TWideStringField;
    qryEntradaCabecalhodatahoraemisao: TSQLTimeStampField;
    qryEntradaCabecalhodatahorasaida: TSQLTimeStampField;
    qryEntradaCabecalhotipooperacao: TBooleanField;
    qryEntradaCabecalhoformatoimpressaodanfe: TWideStringField;
    qryEntradaCabecalhotipoemissao: TWideStringField;
    qryEntradaCabecalhochaveacesso: TWideStringField;
    qryEntradaCabecalhodigitochaveacesso: TWideStringField;
    qryEntradaCabecalhoambiente: TBooleanField;
    qryEntradaCabecalhofinalidadeemissao: TWideStringField;
    qryEntradaCabecalhoprocessoemissao: TWideStringField;
    qryEntradaCabecalhoversaoprocessoemissao: TWideStringField;
    qryEntradaCabecalhodataentradacontingencia: TSQLTimeStampField;
    qryEntradaCabecalhojustificativacontigencia: TWideStringField;
    qryEntradaCabecalhobasecalculoicms: TFloatField;
    qryEntradaCabecalhovaloricms: TFloatField;
    qryEntradaCabecalhobasecalculoicmsst: TFloatField;
    qryEntradaCabecalhovaloricmsst: TFloatField;
    qryEntradaCabecalhovalortotalprodutos: TFloatField;
    qryEntradaCabecalhovalorfrete: TFloatField;
    qryEntradaCabecalhovalorseguro: TFloatField;
    qryEntradaCabecalhovalordesconto: TFloatField;
    qryEntradaCabecalhovaloripi: TFloatField;
    qryEntradaCabecalhovalorpis: TFloatField;
    qryEntradaCabecalhovalorcofins: TFloatField;
    qryEntradaCabecalhovalordespesasacessorias: TFloatField;
    qryEntradaCabecalhovalortotal: TFloatField;
    qryEntradaCabecalhovalorservicos: TFloatField;
    qryEntradaCabecalhobasecalculoissqn: TFloatField;
    qryEntradaCabecalhovalorissqn: TFloatField;
    qryEntradaCabecalhovalorpisissqn: TFloatField;
    qryEntradaCabecalhovalorcofinsissqn: TFloatField;
    qryEntradaCabecalhovalorretidopis: TFloatField;
    qryEntradaCabecalhovalorretidocofins: TFloatField;
    qryEntradaCabecalhobasecalculoirrf: TFloatField;
    qryEntradaCabecalhovalorretidoirrf: TFloatField;
    qryEntradaCabecalhobasecalculoprevidencia: TFloatField;
    qryEntradaCabecalhovalorretidoprevidencia: TFloatField;
    qryEntradaCabecalhoinformacoesadicionaisfisco: TWideMemoField;
    qryEntradaCabecalhoinformacoesaddcontribuinte: TWideMemoField;
    qryEntradaCabecalhofaturanumero: TWideStringField;
    qryEntradaCabecalhofaturavalororiginal: TFloatField;
    qryEntradaCabecalhofaturavalordesconto: TFloatField;
    qryEntradaCabecalhofaturavalorliquido: TFloatField;
    qryEntradaCabecalhoidpessoa: TIntegerField;
    qryEntradaCabecalhoidunidadenegocio: TIntegerField;
    qryEntradaCabecalhonomefantasia: TWideStringField;
    qryEntradaCabecalhopessoanome: TWideStringField;
    qryEntradaTransportadoraidentradatransportadora: TIntegerField;
    qryEntradaTransportadoraidentradacabecalho: TIntegerField;
    qryEntradaTransportadoraidcfop: TIntegerField;
    qryEntradaTransportadoramodalidade: TSmallintField;
    qryEntradaTransportadoracpf_cnpj: TWideStringField;
    qryEntradaTransportadoranome: TWideStringField;
    qryEntradaTransportadorainscricaoestadual: TWideStringField;
    qryEntradaTransportadoraendereco: TWideStringField;
    qryEntradaTransportadoravalorservico: TFloatField;
    qryEntradaTransportadoravalorbcretencaoicms: TFloatField;
    qryEntradaTransportadoraaliquotaretencaoicms: TFloatField;
    qryEntradaTransportadoravaloricmsretido: TFloatField;
    qryEntradaTransportadoravolumequantidade: TSmallintField;
    qryEntradaTransportadoravolumeespecie: TWideStringField;
    qryEntradaTransportadoravolumemarca: TWideStringField;
    qryEntradaTransportadoravolumenumeracao: TWideStringField;
    qryEntradaTransportadoravolumepesoliquido: TFloatField;
    qryEntradaTransportadoravolumepesobruto: TFloatField;
    qryEntradaTransportadoraidpessoa: TIntegerField;
    qryEntradaTransportadorapessoanome: TWideStringField;
    qryEntradaTransportadoraReboqueidentradatransportadorareboque: TIntegerField;
    qryEntradaTransportadoraReboqueidentradacabecalho: TIntegerField;
    qryEntradaTransportadoraReboqueidestado: TWideStringField;
    qryEntradaTransportadoraReboqueplaca: TWideStringField;
    qryEntradaTransportadoraReboquerntc: TWideStringField;
    qryEstadoidestado: TWideStringField;
    qryEstadocodigoibge: TIntegerField;
    qryEstadonome: TWideStringField;
    qryEstadoidpais: TIntegerField;
    qryEstadopaisnome: TWideStringField;
    qryEstoqueContagemDetalheidestoquecotagemdetalhe: TIntegerField;
    qryEstoqueContagemDetalheidestoquecontagemcabecalho: TIntegerField;
    qryEstoqueContagemDetalheidproduto: TIntegerField;
    qryEstoqueContagemDetalhequantidadecontada: TFloatField;
    qryEstoqueContagemDetalhequantidadesistema: TFloatField;
    qryEstoqueContagemDetalhedivergencia: TFloatField;
    qryEstoqueContagemDetalheprodutonome: TWideStringField;
    qryIndicadorEconomicoidindicadoreconomico: TIntegerField;
    qryIndicadorEconomicodescricao: TWideStringField;
    qryIndicadorEconomicoativo: TBooleanField;
    qryIndiceidindice: TIntegerField;
    qryIndiceidindicadoreconomico: TIntegerField;
    qryIndicedataatualizacao: TDateField;
    qryIndicevalor: TFloatField;
    qryIndiceindicadordescricao: TWideStringField;
    qryLicitacaoidlicitacao: TIntegerField;
    qryLicitacaoidpessoa: TIntegerField;
    qryLicitacaodataabertura: TDateField;
    qryLicitacaodatafechamento: TDateField;
    qryLicitacaoobjeto: TWideMemoField;
    qryLicitacaoobservacao: TWideMemoField;
    qryLicitacaoidunidadenegocio: TIntegerField;
    qryLicitacaopessoanome: TWideStringField;
    qryLicitacaonomefantasia: TWideStringField;
    qryLicitacaoDocumentoidlicitacaodocumento: TIntegerField;
    qryLicitacaoDocumentoiddocumento: TIntegerField;
    qryLicitacaoDocumentoidlicitacao: TIntegerField;
    qryModeloidmodelo: TWideStringField;
    qryModelodescricao: TWideStringField;
    qryMovimentoidmovimento: TIntegerField;
    qryMovimentoidnfeduplicata: TIntegerField;
    qryMovimentoidplanocontasfinanceiro: TIntegerField;
    qryMovimentoidplanocontasgerencial: TIntegerField;
    qryMovimentoidhistoricomovimento: TIntegerField;
    qryMovimentoidportador: TIntegerField;
    qryMovimentoidpessoa: TIntegerField;
    qryMovimentodataregistro: TDateField;
    qryMovimentodatavencimento: TDateField;
    qryMovimentodataliquidacao: TDateField;
    qryMovimentoorigem: TWideStringField;
    qryMovimentonf: TIntegerField;
    qryMovimentofatura: TWideStringField;
    qryMovimentocontrapartida: TIntegerField;
    qryMovimentosituacao: TWideStringField;
    qryMovimentojurovalor: TFloatField;
    qryMovimentomultavalor: TFloatField;
    qryMovimentovalor: TFloatField;
    qryMovimentovalorsaldo: TFloatField;
    qryMovimentoidunidadenegocio: TIntegerField;
    qryMovimentoplanofinanceirodescricao: TWideStringField;
    qryMovimentoplanogerencialdescricao: TWideStringField;
    qryMovimentoportadordescricao: TWideStringField;
    qryMovimentonomefantasia: TWideStringField;
    qryMovimentopessoanome: TWideStringField;
    qryMovimentoChequeidmovimentocheque: TIntegerField;
    qryMovimentoChequeidbanco: TWideStringField;
    qryMovimentoChequeidmovimento: TIntegerField;
    qryMovimentoChequeagencia: TSmallintField;
    qryMovimentoChequeagenciadigito: TWideStringField;
    qryMovimentoChequeconta: TSmallintField;
    qryMovimentoChequecontadigito: TWideStringField;
    qryMovimentoChequenumero: TWideStringField;
    qryMovimentoChequebanconome: TWideStringField;
    qryMunicipioidmunicipio: TIntegerField;
    qryMunicipionome: TWideStringField;
    qryMunicipioidestado: TWideStringField;
    qryNCMidncm: TIntegerField;
    qryNCMdescricao: TWideStringField;
    qryNFeCabecalhoidnfecabecalho: TIntegerField;
    qryNFeCabecalhoidserie: TIntegerField;
    qryNFeCabecalhoidmodelo: TWideStringField;
    qryNFeCabecalhoufemitente: TWideStringField;
    qryNFeCabecalhocodigonumerico: TWideStringField;
    qryNFeCabecalhonaturezaoperacao: TIntegerField;
    qryNFeCabecalhoindicadorformapagamento: TBooleanField;
    qryNFeCabecalhonumero: TWideStringField;
    qryNFeCabecalhodatahoraemisao: TSQLTimeStampField;
    qryNFeCabecalhodatahorasaida: TSQLTimeStampField;
    qryNFeCabecalhotipooperacao: TBooleanField;
    qryNFeCabecalhoformatoimpressaodanfe: TWideStringField;
    qryNFeCabecalhotipoemissao: TWideStringField;
    qryNFeCabecalhochaveacesso: TWideStringField;
    qryNFeCabecalhodigitochaveacesso: TWideStringField;
    qryNFeCabecalhoambiente: TBooleanField;
    qryNFeCabecalhofinalidadeemissao: TWideStringField;
    qryNFeCabecalhoprocessoemissao: TWideStringField;
    qryNFeCabecalhoversaoprocessoemissao: TWideStringField;
    qryNFeCabecalhodataentradacontingencia: TSQLTimeStampField;
    qryNFeCabecalhojustificativacontigencia: TWideStringField;
    qryNFeCabecalhobasecalculoicms: TFloatField;
    qryNFeCabecalhovaloricms: TFloatField;
    qryNFeCabecalhobasecalculoicmsst: TFloatField;
    qryNFeCabecalhovaloricmsst: TFloatField;
    qryNFeCabecalhovalortotalprodutos: TFloatField;
    qryNFeCabecalhovalorfrete: TFloatField;
    qryNFeCabecalhovalorseguro: TFloatField;
    qryNFeCabecalhovalordesconto: TFloatField;
    qryNFeCabecalhovalorimpostoimportacao: TFloatField;
    qryNFeCabecalhovaloripi: TFloatField;
    qryNFeCabecalhovalorpis: TFloatField;
    qryNFeCabecalhovalorcofins: TFloatField;
    qryNFeCabecalhovalordespesasacessorias: TFloatField;
    qryNFeCabecalhovalortotal: TFloatField;
    qryNFeCabecalhovalorservicos: TFloatField;
    qryNFeCabecalhobasecalculoissqn: TFloatField;
    qryNFeCabecalhovalorissqn: TFloatField;
    qryNFeCabecalhovalorpisissqn: TFloatField;
    qryNFeCabecalhovalorcofinsissqn: TFloatField;
    qryNFeCabecalhovalorretidopis: TFloatField;
    qryNFeCabecalhovalorretidocofins: TFloatField;
    qryNFeCabecalhobasecalculoirrf: TFloatField;
    qryNFeCabecalhovalorretidoirrf: TFloatField;
    qryNFeCabecalhobasecalculoprevidencia: TFloatField;
    qryNFeCabecalhovalorretidoprevidencia: TFloatField;
    qryNFeCabecalhocomexufembarque: TWideStringField;
    qryNFeCabecalhocomexlocalembarque: TWideStringField;
    qryNFeCabecalhoinformacoesadicionaisfisco: TWideMemoField;
    qryNFeCabecalhoinformacoesaddcontribuinte: TWideMemoField;
    qryNFeCabecalhostatusnota: TWideStringField;
    qryNFeCabecalhofaturanumero: TWideStringField;
    qryNFeCabecalhofaturavalororiginal: TFloatField;
    qryNFeCabecalhofaturavalordesconto: TFloatField;
    qryNFeCabecalhofaturavalorliquido: TFloatField;
    qryNFeCabecalhoidunidadenegocio: TIntegerField;
    qryNFeCabecalhonomefantasia: TWideStringField;
    qryNFeCupomFiscalReferenciadoidnfecupomfiscalreferenciado: TIntegerField;
    qryNFeCupomFiscalReferenciadoidnfecabecalho: TIntegerField;
    qryNFeCupomFiscalReferenciadomodelodocumentofiscal: TWideStringField;
    qryNFeCupomFiscalReferenciadonumeroordemecf: TIntegerField;
    qryNFeCupomFiscalReferenciadocoo: TIntegerField;
    qryNFeCupomFiscalReferenciadodataemissaocupom: TDateField;
    qryNFeCupomFiscalReferenciadonumerocaixa: TIntegerField;
    qryNFeCupomFiscalReferenciadonumeroserieecf: TWideStringField;
    qryNFeDeclaracaoImportacaoidnfedeclaracaoimportacao: TIntegerField;
    qryNFeDeclaracaoImportacaoidnfeitem: TIntegerField;
    qryNFeDeclaracaoImportacaonumerdocumento: TWideStringField;
    qryNFeDeclaracaoImportacaodataregistro: TDateField;
    qryNFeDeclaracaoImportacaolocaldesembaraco: TWideStringField;
    qryNFeDeclaracaoImportacaouf: TWideStringField;
    qryNFeDeclaracaoImportacaodatadesembaraco: TDateField;
    qryNFeDeclaracaoImportacaocodigoexportador: TWideStringField;
    qryNFeDestinatarioidnfedestinatario: TIntegerField;
    qryNFeDestinatarioidnfecabecalho: TIntegerField;
    qryNFeDestinatarioidcep: TWideStringField;
    qryNFeDestinatarioidpais: TIntegerField;
    qryNFeDestinatarioidmunicipio: TIntegerField;
    qryNFeDestinatarioidestado: TWideStringField;
    qryNFeDestinatariocpf_cnpj: TWideStringField;
    qryNFeDestinatariorazaosocial: TWideStringField;
    qryNFeDestinatariologradouro: TWideStringField;
    qryNFeDestinatarionumero: TWideStringField;
    qryNFeDestinatariocomplemento: TWideStringField;
    qryNFeDestinatariobairro: TWideStringField;
    qryNFeDestinatariotelefone: TWideStringField;
    qryNFeDestinatarioinscricaoestadual: TWideStringField;
    qryNFeDestinatariosuframa: TWideStringField;
    qryNFeDestinatarioemail: TWideStringField;
    qryNFeDestinatariopaisnome: TWideStringField;
    qryNFeDestinatariomunicipionome: TWideStringField;
    qryNFeDuplicataidnfeduplicata: TIntegerField;
    qryNFeDuplicataidnfecabecalho: TIntegerField;
    qryNFeDuplicatanumero: TWideStringField;
    qryNFeDuplicatavalor: TFloatField;
    qryNFeDuplicatadatavencimento: TDateField;
    qryNFeImportacaoDetalheidnfeimportacaodetalhe: TIntegerField;
    qryNFeImportacaoDetalheidnfedeclaracaoimportacao: TIntegerField;
    qryNFeImportacaoDetalhenumeroadicao: TIntegerField;
    qryNFeImportacaoDetalhenumerosequencial: TIntegerField;
    qryNFeImportacaoDetalhecodigofabricanteestrangeiro: TWideStringField;
    qryNFeImportacaoDetalhevalordesconto: TFloatField;
    qryNFeItemidnfeitem: TIntegerField;
    qryNFeItemidnfecabecalho: TIntegerField;
    qryNFeItemidproduto: TIntegerField;
    qryNFeItemnumeroitem: TIntegerField;
    qryNFeItemcodigoproduto: TWideStringField;
    qryNFeItemgtin: TWideStringField;
    qryNFeItemdescricaoproduto: TWideStringField;
    qryNFeItemncm: TIntegerField;
    qryNFeItemextipi: TIntegerField;
    qryNFeItemcfop: TIntegerField;
    qryNFeItemunidadecomercial: TWideStringField;
    qryNFeItemquantidadecomercial: TFloatField;
    qryNFeItemvaloriunitariocomercial: TFloatField;
    qryNFeItemvalorbrutoproduto: TFloatField;
    qryNFeItemunidadetributavel: TWideStringField;
    qryNFeItemquantidadetributavel: TFloatField;
    qryNFeItemvalorunitariotributavel: TFloatField;
    qryNFeItemvalorfrete: TFloatField;
    qryNFeItemvalorseguro: TFloatField;
    qryNFeItemvalordesconto: TFloatField;
    qryNFeItemvaloroutrasdespesas: TFloatField;
    qryNFeItementratotal: TBooleanField;
    qryNFeItemvalorsubtotal: TFloatField;
    qryNFeItemvalortotal: TFloatField;
    qryNFeItemnumeropedido: TIntegerField;
    qryNFeItemitempedido: TIntegerField;
    qryNFeIteminformacoesadicionais: TWideMemoField;
    qryNFeItemprodutonome: TWideStringField;
    qryNFeItemIIidnfeitemii: TIntegerField;
    qryNFeItemIIidnfeitem: TIntegerField;
    qryNFeItemIIbcvalor: TFloatField;
    qryNFeItemIIvalordespesasaduaneiras: TFloatField;
    qryNFeItemIIvalorimposto: TFloatField;
    qryNFeItemIIvaloriof: TFloatField;
    qryNFeItemImpostoidnfeitemimposto: TIntegerField;
    qryNFeItemImpostoidnfeitem: TIntegerField;
    qryNFeItemImpostoorigemmercadoria: TSmallintField;
    qryNFeItemImpostoicmscst: TSmallintField;
    qryNFeItemImpostocsosn: TSmallintField;
    qryNFeItemImpostoicmsmodalidadebc: TSmallintField;
    qryNFeItemImpostoicmsreducaobc: TFloatField;
    qryNFeItemImpostoicmsbasecalculo: TFloatField;
    qryNFeItemImpostoicmsaliquota: TFloatField;
    qryNFeItemImpostoicmsvalor: TFloatField;
    qryNFeItemImpostoicmsmotivodesoneracao: TWideStringField;
    qryNFeItemImpostoicmsmodalidadebcst: TSmallintField;
    qryNFeItemImpostoicmsmvast: TFloatField;
    qryNFeItemImpostoicmsreducaobcst: TFloatField;
    qryNFeItemImpostoicmsvalorbcst: TFloatField;
    qryNFeItemImpostoicmsaliquotast: TFloatField;
    qryNFeItemImpostoicmsvalorst: TFloatField;
    qryNFeItemImpostoicmsvalorbcstretido: TFloatField;
    qryNFeItemImpostoicmsvalorstretido: TFloatField;
    qryNFeItemImpostoicmsvalorbcstdestino: TFloatField;
    qryNFeItemImpostoicmsvalorstdestino: TFloatField;
    qryNFeItemImpostoicmsaliquotacreditosn: TFloatField;
    qryNFeItemImpostoicmsvalorcreditosn: TFloatField;
    qryNFeItemImpostoprecentualbcoperacaopropria: TFloatField;
    qryNFeItemImpostoufst: TWideStringField;
    qryNFeItemImpostoipienquadramento: TWideStringField;
    qryNFeItemImpostoipicnpjprodutor: TWideStringField;
    qryNFeItemImpostoipicst: TSmallintField;
    qryNFeItemImpostoipivalorbc: TFloatField;
    qryNFeItemImpostoipialiquota: TFloatField;
    qryNFeItemImpostoipiquantidadeunidadetributavel: TFloatField;
    qryNFeItemImpostoipivalorunidadetributavel: TFloatField;
    qryNFeItemImpostoipivalor: TFloatField;
    qryNFeItemImpostocofinscst: TSmallintField;
    qryNFeItemImpostocofinsquantidadevendida: TFloatField;
    qryNFeItemImpostocofinsbc: TFloatField;
    qryNFeItemImpostocofinsaliquotapercentual: TFloatField;
    qryNFeItemImpostocofinsaliquotavalor: TFloatField;
    qryNFeItemImpostocofinsvalor: TFloatField;
    qryNFeItemImpostopiscst: TSmallintField;
    qryNFeItemImpostopisquantidadevalor: TFloatField;
    qryNFeItemImpostopisbc: TFloatField;
    qryNFeItemImpostopisaliquotapercentual: TFloatField;
    qryNFeItemImpostopisaliquotavalor: TFloatField;
    qryNFeItemImpostopisvalor: TFloatField;
    qryNFeItemImpostoissbc: TFloatField;
    qryNFeItemImpostoissaliquota: TFloatField;
    qryNFeItemImpostoissvalor: TFloatField;
    qryNFeItemImpostoissmunicipio: TIntegerField;
    qryNFeItemImpostoissitemlistaservico: TIntegerField;
    qryNFeItemImpostoisstributacao: TSmallintField;
    qryNFeLocalEntregaRetiradaidnfelocalentregaretirada: TIntegerField;
    qryNFeLocalEntregaRetiradaidnfecabecalho: TIntegerField;
    qryNFeLocalEntregaRetiradacpf_cnpj: TWideStringField;
    qryNFeLocalEntregaRetiradalogradouro: TWideStringField;
    qryNFeLocalEntregaRetiradanumero: TWideStringField;
    qryNFeLocalEntregaRetiradacomplemento: TWideStringField;
    qryNFeLocalEntregaRetiradabairro: TWideStringField;
    qryNFeLocalEntregaRetiradatipo: TWideStringField;
    qryNFeNFReferenciadaidnfenfreferenciada: TIntegerField;
    qryNFeNFReferenciadaidnfecabecalho: TIntegerField;
    qryNFeNFReferenciadaanomes: TWideStringField;
    qryNFeNFReferenciadacnpj: TWideStringField;
    qryNFeNFReferenciadamodelo: TWideStringField;
    qryNFeNFReferenciadaserie: TWideStringField;
    qryNFeNFReferenciadanumeronf: TIntegerField;
    qryNFeProdutorRuralReferenciadaidnfeprodutorruralreferenciada: TIntegerField;
    qryNFeProdutorRuralReferenciadaidnfecabecalho: TIntegerField;
    qryNFeProdutorRuralReferenciadaanomes: TWideStringField;
    qryNFeProdutorRuralReferenciadacnpj: TWideStringField;
    qryNFeProdutorRuralReferenciadacpf: TWideStringField;
    qryNFeProdutorRuralReferenciadainscricaoestadual: TWideStringField;
    qryNFeProdutorRuralReferenciadamodelo: TWideStringField;
    qryNFeProdutorRuralReferenciadaserie: TWideStringField;
    qryNFeProdutorRuralReferenciadanumeronf: TIntegerField;
    qryNFeReferenciadaidnfereferenciada: TIntegerField;
    qryNFeReferenciadaidnfecabecalho: TIntegerField;
    qryNFeReferenciadachaveacesso: TWideStringField;
    qryNFeTransportadoraidnfetransportadora: TIntegerField;
    qryNFeTransportadoraidnfecabecalho: TIntegerField;
    qryNFeTransportadoraidestado: TWideStringField;
    qryNFeTransportadoraidcfop: TIntegerField;
    qryNFeTransportadoraidmunicipio: TIntegerField;
    qryNFeTransportadoramodalidade: TSmallintField;
    qryNFeTransportadoracpf_cnpj: TWideStringField;
    qryNFeTransportadoranome: TWideStringField;
    qryNFeTransportadorainscricaoestadual: TWideStringField;
    qryNFeTransportadoraendereco: TWideStringField;
    qryNFeTransportadoravalorservico: TFloatField;
    qryNFeTransportadoravalorbcretencaoicms: TFloatField;
    qryNFeTransportadoraaliquotaretencaoicms: TFloatField;
    qryNFeTransportadoravaloricmsretido: TFloatField;
    qryNFeTransportadoravolumequantidade: TSmallintField;
    qryNFeTransportadoravolumeespecie: TWideStringField;
    qryNFeTransportadoravolumemarca: TWideStringField;
    qryNFeTransportadoravolumenumeracao: TWideStringField;
    qryNFeTransportadoravolumepesoliquido: TFloatField;
    qryNFeTransportadoravolumepesobruto: TFloatField;
    qryNFeTransportadoramunicipionome: TWideStringField;
    qryNFeTransportadoracfopdescricao: TWideStringField;
    qryNFeTransportadoraReboqueidnfetransportadorareboque: TIntegerField;
    qryNFeTransportadoraReboqueidnfecabecalho: TIntegerField;
    qryNFeTransportadoraReboqueidestado: TWideStringField;
    qryNFeTransportadoraReboqueplaca: TWideStringField;
    qryNFeTransportadoraReboquerntc: TWideStringField;
    qryOrcamentoCabecalhoidorcamentocabecalho: TIntegerField;
    qryOrcamentoCabecalhoidlicitacao: TIntegerField;
    qryOrcamentoCabecalhoidpessoa: TIntegerField;
    qryOrcamentoCabecalhodatacadastro: TDateField;
    qryOrcamentoCabecalhodataentrega: TDateField;
    qryOrcamentoCabecalhotipofrete: TWideStringField;
    qryOrcamentoCabecalhovalorsubtotal: TFloatField;
    qryOrcamentoCabecalhovalorfrete: TFloatField;
    qryOrcamentoCabecalhotaxacomissao: TFloatField;
    qryOrcamentoCabecalhovalorcomicao: TFloatField;
    qryOrcamentoCabecalhotaxadesconto: TFloatField;
    qryOrcamentoCabecalhovalordesconto: TFloatField;
    qryOrcamentoCabecalhovalortotal: TFloatField;
    qryOrcamentoCabecalhoobservacao: TWideMemoField;
    qryOrcamentoCabecalhosituacao: TWideStringField;
    qryOrcamentoCabecalhoidunidadenegocio: TIntegerField;
    qryOrcamentoCabecalhonomefantasia: TWideStringField;
    qryOrcamentoCabecalhopessoanome: TWideStringField;
    qryOrcamentoItemidorcamentoitem: TIntegerField;
    qryOrcamentoItemidorcamentocabecalho: TIntegerField;
    qryOrcamentoItemidproduto: TIntegerField;
    qryOrcamentoItemquantidade: TFloatField;
    qryOrcamentoItemvalorunitario: TFloatField;
    qryOrcamentoItemvalorsubtotal: TFloatField;
    qryOrcamentoItemtaxadesconto: TFloatField;
    qryOrcamentoItemvalordesconto: TFloatField;
    qryOrcamentoItemvalortotal: TFloatField;
    qryOrcamentoItemprodutonome: TWideStringField;
    qryPaisidpais: TIntegerField;
    qryPaisidindicadoreconomico: TIntegerField;
    qryPaisnome: TWideStringField;
    qryPaisindicadordescricao: TWideStringField;
    qryPedidoCabecalhoidpedidocabecalho: TIntegerField;
    qryPedidoCabecalhoidunidadenegocio: TIntegerField;
    qryPedidoCabecalhoidpessoa: TIntegerField;
    qryPedidoCabecalhoidorcamentocabecalho: TIntegerField;
    qryPedidoCabecalhodatalancamento: TDateField;
    qryPedidoCabecalhodataprevisaoentrega: TDateField;
    qryPedidoCabecalhovalorsubtotal: TFloatField;
    qryPedidoCabecalhotaxacomicao: TFloatField;
    qryPedidoCabecalhovalorcomicao: TFloatField;
    qryPedidoCabecalhotaxadesconto: TFloatField;
    qryPedidoCabecalhovalordesconto: TFloatField;
    qryPedidoCabecalhovalorfrete: TFloatField;
    qryPedidoCabecalhotipofrete: TFloatField;
    qryPedidoCabecalhovalorseguro: TFloatField;
    qryPedidoCabecalhoobservacao: TWideMemoField;
    qryPedidoCabecalhosituacao: TWideStringField;
    qryPedidoCabecalhonomefantasia: TWideStringField;
    qryPedidoCabecalhopessoanome: TWideStringField;
    qryPedidoItemidpedidoitem: TIntegerField;
    qryPedidoItemidproduto: TIntegerField;
    qryPedidoItemidpedidocabecalho: TIntegerField;
    qryPedidoItemquantidade: TFloatField;
    qryPedidoItemvalorunitario: TFloatField;
    qryPedidoItemvalorsubtotal: TFloatField;
    qryPedidoItemtaxadesconto: TFloatField;
    qryPedidoItemvalordesconto: TFloatField;
    qryPedidoItemvalortotal: TFloatField;
    qryPedidoItemprodutonome: TWideStringField;
    qryPessoaidpessoa: TIntegerField;
    qryPessoatipo: TWideStringField;
    qryPessoaemail: TWideStringField;
    qryPessoasite: TWideStringField;
    qryPessoacliente2: TBooleanField;
    qryPessoafornecedor2: TBooleanField;
    qryPessoacolaborador2: TBooleanField;
    qryPessoacontador2: TBooleanField;
    qryPessoatransportadora2: TBooleanField;
    qryPessoavendedor2: TBooleanField;
    qryPessoacpf: TWideStringField;
    qryPessoacnpj: TWideStringField;
    qryPessoarg: TWideStringField;
    qryPessoadatanascimento: TDateField;
    qryPessoasexo: TWideStringField;
    qryPessoaestadocivil: TWideStringField;
    qryPessoacnhnumero: TWideStringField;
    qryPessoacnhcategoria: TWideStringField;
    qryPessoacnhvencimento: TDateField;
    qryPessoanomemae: TWideStringField;
    qryPessoanomepai: TWideStringField;
    qryPessoanomefantasia: TWideStringField;
    qryPessoainscricaomunicipal: TWideStringField;
    qryPessoainscricaoestadual: TWideStringField;
    qryPessoatiporegime: TWideStringField;
    qryPessoacrt: TWideStringField;
    qryPessoasuframa: TWideStringField;
    qryPessoanome: TWideStringField;
    qryPessoaClienteidpessoa: TIntegerField;
    qryPessoaClientedatacadastro: TDateField;
    qryPessoaClienteobservacao: TWideMemoField;
    qryPessoaClientegerafinanceiro: TBooleanField;
    qryPessoaClientelimitecredito: TFloatField;
    qryPessoaClienteativo: TBooleanField;
    qryPessoaClienteestadocivil: TWideStringField;
    qryPessoaColaboradoridbanco: TWideStringField;
    qryPessoaColaboradoridsetor: TIntegerField;
    qryPessoaColaboradoridcargo: TIntegerField;
    qryPessoaColaboradoridpessoa: TIntegerField;
    qryPessoaColaboradormatricula: TWideStringField;
    qryPessoaColaboradorfoto3x4: TWideMemoField;
    qryPessoaColaboradordatacadastro: TDateField;
    qryPessoaColaboradordataadmissao: TDateField;
    qryPessoaColaboradorfgtsconta: TSmallintField;
    qryPessoaColaboradorformapagamento: TWideStringField;
    qryPessoaColaboradorexamedata: TDateField;
    qryPessoaColaboradorexamedataultimo: TDateField;
    qryPessoaColaboradorctpsnumero: TWideStringField;
    qryPessoaColaboradorctpsserie: TWideStringField;
    qryPessoaColaboradorctpsdataexpedicao: TDateField;
    qryPessoaColaboradorctpsuf: TWideStringField;
    qryPessoaColaboradorobservacao: TWideMemoField;
    qryPessoaColaboradordatademissao: TDateField;
    qryPessoaColaboradoridunidadenegocio: TIntegerField;
    qryPessoaColaboradorsetornome: TWideStringField;
    qryPessoaColaboradorcargonome: TWideStringField;
    qryPessoaContadoridpessoa: TIntegerField;
    qryPessoaContadornome: TWideStringField;
    qryPessoaContadorcpf: TWideStringField;
    qryPessoaContadorcrc: TWideStringField;
    qryPessoaContadoremail: TWideStringField;
    qryPessoaContadoridunidadenegocio: TIntegerField;
    qryPessoaFornecedoridpessoafornecedor: TIntegerField;
    qryPessoaFornecedoridpessoa: TIntegerField;
    qryPessoaFornecedordesde: TDateField;
    qryPessoaFornecedoroptandesimples: TBooleanField;
    qryPessoaFornecedorlocalizacao: TBooleanField;
    qryPessoaFornecedordatacadastro: TDateField;
    qryPessoaFornecedorsofreretencao: TBooleanField;
    qryPessoaFornecedorobservacao: TWideMemoField;
    qryPessoaFornecedorprazomedioentrega: TIntegerField;
    qryPessoaFornecedorgerafaturamento: TBooleanField;
    qryPessoaFornecedornumerodiasprimeirovencimento: TIntegerField;
    qryPessoaFornecedornumerodiasintervalo: TIntegerField;
    qryPessoaFornecedorquantidadeparcelas: TIntegerField;
    qryPessoaTransportadoraidpessoa: TIntegerField;
    qryPessoaTransportadoradatacadastro: TDateField;
    qryPessoaTransportadoraobservacao: TWideMemoField;
    qryPessoaVendedoridpessoa: TIntegerField;
    qryPessoaVendedorcomissao: TFloatField;
    qryPessoaVendedormetavendas: TFloatField;
    qryPessoaVendedoridunidadenegocio: TIntegerField;
    qryPessoaVendedornomefantasia: TWideStringField;
    qryPessoaRepresentanteidpessoa: TIntegerField;
    qryPessoaRepresentantecomissao: TFloatField;
    qryPessoaRepresentantemetavendas: TFloatField;
    qryPessoaRepresentanteidunidadenegocio: TIntegerField;
    qryPessoaRepresentantenomefantasia: TWideStringField;
    qryPessoaContadornomefantasia: TWideStringField;
    qryPlanoContasFinanceiroidplanocontasfinanceiro: TIntegerField;
    qryPlanoContasFinanceirocodigo: TWideStringField;
    qryPlanoContasFinanceirodescricao: TWideStringField;
    qryPlanoContasFinanceirotipo: TWideStringField;
    qryPlanoContasFinanceiroativo: TBooleanField;
    qryPlanoContasGerencialidplanocontasgerencial: TIntegerField;
    qryPlanoContasGerencialcodigo: TWideStringField;
    qryPlanoContasGerencialdescricao: TWideStringField;
    qryPlanoContasGerencialtipo: TWideStringField;
    qryPlanoContasGerencialnivel: TSmallintField;
    qryPlanoContasGerencialativo: TBooleanField;
    qryPortadoridportador: TIntegerField;
    qryPortadoridbanco: TWideStringField;
    qryPortadordescricao: TWideStringField;
    qryPortadorbanconome: TWideStringField;
    qryPortadorHistoricoidportadorhistorico: TIntegerField;
    qryPortadorHistoricoidportador: TIntegerField;
    qryPortadorHistoricodatamovimento: TDateField;
    qryPortadorHistoricosaldoinicial: TFloatField;
    qryPortadorHistoricoentrada: TFloatField;
    qryPortadorHistoricosaida: TFloatField;
    qryPortadorHistoricosaldofinal: TFloatField;
    qryProdutoidproduto: TIntegerField;
    qryProdutoidgrupoprodutos: TIntegerField;
    qryProdutoidsubgrupoprodutos: TIntegerField;
    qryProdutoidncm: TIntegerField;
    qryProdutoidprodutounidade: TIntegerField;
    qryProdutocodigointerno: TWideStringField;
    qryProdutogetin: TWideStringField;
    qryProdutonome: TWideStringField;
    qryProdutodescricao: TWideMemoField;
    qryProdutodescricaopdv: TWideStringField;
    qryProdutovalorcompra: TFloatField;
    qryProdutovalorvenda: TFloatField;
    qryProdutoprecovendaminimo: TFloatField;
    qryProdutoprecosugerido: TFloatField;
    qryProdutocustomedioliquido: TFloatField;
    qryProdutoprecolucrozero: TFloatField;
    qryProdutoprecolucrominimo: TFloatField;
    qryProdutoprecolucromaximo: TFloatField;
    qryProdutomarkup: TFloatField;
    qryProdutoquantidadeestoque: TFloatField;
    qryProdutoestoqueminimo: TFloatField;
    qryProdutoestoquemaximo: TFloatField;
    qryProdutoestoqueideal: TFloatField;
    qryProdutodatacadastro: TDateField;
    qryProdutofotoproduto: TWideMemoField;
    qryProdutocodigobalanca: TIntegerField;
    qryProdutotipo: TWideStringField;
    qryProdutoclasseabc: TWideStringField;
    qryProdutocodigolst: TWideStringField;
    qryProdutopeso: TFloatField;
    qryProdutopercentualcomissao: TFloatField;
    qryProdutoinativo: TWideStringField;
    qryProdutogruponome: TWideStringField;
    qryProdutosubgruponome: TWideStringField;
    qryProdutoFornecedoridprodutofornecedor: TIntegerField;
    qryProdutoFornecedorcodigoprodutofornecedor: TWideStringField;
    qryProdutoFornecedoridproduto: TIntegerField;
    qryProdutoFornecedordataultimacompra: TDateField;
    qryProdutoFornecedorprecoultimacompra: TFloatField;
    qryProdutoGrupoidgrupoprodutos: TIntegerField;
    qryProdutoGruponome2: TWideStringField;
    qryProdutoGrupodescricao: TWideMemoField;
    qryProdutoPromocaoidprodutopromocao: TIntegerField;
    qryProdutoPromocaoidproduto: TIntegerField;
    qryProdutoPromocaodatainicio: TDateField;
    qryProdutoPromocaodatafim: TDateField;
    qryProdutoPromocaoquantidadeempromocao: TFMTBCDField;
    qryProdutoPromocaoquantidademaximacliente: TFMTBCDField;
    qryProdutoPromocaovalor: TFMTBCDField;
    qryProdutoPromocaoprodutonome: TWideStringField;
    qryProdutoSubGrupoidsubgrupoprodutos: TIntegerField;
    qryProdutoSubGrupoidgrupoprodutos: TIntegerField;
    qryProdutoSubGruponome2: TWideStringField;
    qryProdutoSubGrupodescricao: TWideMemoField;
    qryProdutoSubGrupogruponome: TWideStringField;
    qryProdutoTabelaPrecoidprodutotabelapreco: TIntegerField;
    qryProdutoTabelaPrecoidproduto: TIntegerField;
    qryProdutoTabelaPreconome: TWideStringField;
    qryProdutoTabelaPrecopreco: TFloatField;
    qryProdutoTabelaPrecoprodutonome: TWideStringField;
    qryProdutoUnidadeidprodutounidade: TIntegerField;
    qryProdutoUnidadesigla: TWideStringField;
    qryProdutoUnidadedescricao: TWideMemoField;
    qryProdutoUnidadeConversaoidprodutounidadeconversao: TIntegerField;
    qryProdutoUnidadeConversaoidproduto: TIntegerField;
    qryProdutoUnidadeConversaoidprodutounidade: TIntegerField;
    qryProdutoUnidadeConversaosigla: TWideStringField;
    qryProdutoUnidadeConversaodescricao: TWideMemoField;
    qryProdutoUnidadeConversaofatorconversao: TFloatField;
    qryProdutoUnidadeConversaoprodutonome: TWideStringField;
    qryProdutoUnidadeConversaounidadesigla: TWideStringField;
    qryRegraFiscalidregrafiscal: TIntegerField;
    qryRegraFiscalidpessoa: TIntegerField;
    qryRegraFiscalidregrafiscalobservacao: TIntegerField;
    qryRegraFiscalidcstpis: TIntegerField;
    qryRegraFiscalidcstipi: TIntegerField;
    qryRegraFiscalidtipooperacao: TIntegerField;
    qryRegraFiscalidpais: TIntegerField;
    qryRegraFiscalidmunicipio: TIntegerField;
    qryRegraFiscalidestado: TWideStringField;
    qryRegraFiscalidunidadenegocio: TIntegerField;
    qryRegraFiscalidcfop: TIntegerField;
    qryRegraFiscalidncm: TIntegerField;
    qryRegraFiscalidcstcofins: TIntegerField;
    qryRegraFiscalreducaoipi: TFloatField;
    qryRegraFiscalipi: TSmallintField;
    qryRegraFiscalreducaoicms: TFloatField;
    qryRegraFiscalicms: TSmallintField;
    qryRegraFiscalpis: TFloatField;
    qryRegraFiscalretencaopis: TFloatField;
    qryRegraFiscalcofins: TFloatField;
    qryRegraFiscalretencaocofins: TIntegerField;
    qryRegraFiscalativo: TBooleanField;
    qryRegraFiscalmva: TFloatField;
    qryRegraFiscalst: TFloatField;
    qryRegraFiscalreducaost: TFloatField;
    qryRegraFiscaliss: TFloatField;
    qryRegraFiscalreducaoiss: TFloatField;
    qryRegraFiscalcsosn: TSmallintField;
    qryRegraFiscalcssl: TFloatField;
    qryRegraFiscalinss: TFloatField;
    qryRegraFiscalir: TSmallintField;
    qryRegraFiscalfunrural: TFloatField;
    qryRegraFiscalie: TFloatField;
    qryRegraFiscalii: TFloatField;
    qryRegraFiscalcfopdevolucao: TSmallintField;
    qryRegraFiscalpessoanome: TWideStringField;
    qryRegraFiscalcstpisdescricao: TWideStringField;
    qryRegraFiscalcstipidescricao: TWideStringField;
    qryRegraFiscaltipooperacaodescricao: TWideStringField;
    qryRegraFiscalpaisnome: TWideStringField;
    qryRegraFiscalmunicipionome: TWideStringField;
    qryRegraFiscalnomefantasia: TWideStringField;
    qryRegraFiscalcfopdescricao: TWideStringField;
    qryRegraFiscalncmdescricao: TWideStringField;
    qryRegraFiscalcstcofinsdescricao: TWideStringField;
    qryRegraFiscalObservacaoidregrafiscalobservacao: TIntegerField;
    qryRegraFiscalObservacaoobservacao: TWideMemoField;
    qrySetoridsetor: TIntegerField;
    qrySetornome: TWideStringField;
    qrySetordescricao: TWideStringField;
    qryTelefoneidtelefone: TIntegerField;
    qryTelefoneidpessoa: TIntegerField;
    qryTelefoneidunidadenegocio: TIntegerField;
    qryTelefoneidtipotelefone: TIntegerField;
    qryTelefonenumerotelefone: TWideStringField;
    qryTipoTelefoneidtipotelefone: TIntegerField;
    qryTipoTelefonedescricao: TWideStringField;
    qryUnidadeNegocioidunidadenegocio: TIntegerField;
    qryUnidadeNegocioidcnae: TIntegerField;
    qryUnidadeNegocioidempresa: TIntegerField;
    qryUnidadeNegociocnpj: TWideStringField;
    qryUnidadeNegocionomefantasia: TWideStringField;
    qryUnidadeNegociocnaedenominacao: TWideMemoField;
    qryUnidadeNegociorazaosocial: TWideStringField;
    procedure DSServerModuleCreate(Sender: TObject);
  private
    { Private declarations }
    //Funções para gestão do Arquivo LOG - DJD
    procedure LOGopen;
    procedure LOGclose;
    procedure LOGadd(msg: String);
    //Função para alterar SQL da Query e retornar ao cliente - DJD
    procedure alteraSQL(Query : TFDQuery; filtro, select, from, where, order:String);

    //Constantes com as definições das SQLs inicias de cada tabela - DJD
    //const select[NOMEDATABELA]: array[1..5] of string = ([SELECT],[FROM],[WHERE],[ORDER],[LIMIT]);
    const selectAuditoria: array[1..5] of string = ('','','','',' limit 0 ');
    const selectBanco: array[1..5] of string = ('','','','',' limit 0 ');
    const selectCargo: array[1..5] of string = ('','','','',' limit 0 ');
    const selectCBO: array[1..5] of string = ('','','','',' limit 0 ');
    const selectCEP: array[1..5] of string = ('','','','',' limit 0 ');
    const selectCFOP: array[1..5] of string = ('','','','',' limit 0 ');
    const selectCNAE: array[1..5] of string = ('','','','',' limit 0 ');
    const selectControle: array[1..5] of string = ('','','','',' limit 0 ');
    const selectCSTCOFINS: array[1..5] of string = ('','','','',' limit 0 ');
    const selectCSTIPI: array[1..5] of string = ('','','','',' limit 0 ');
    const selectCSTPIS: array[1..5] of string = ('','','','',' limit 0 ');
    const selectDocumento: array[1..5] of string = ('','','','',' limit 0 ');
    const selectECFCabecalho: array[1..5] of string = ('','','','',' limit 0 ');
    const selectECFItem: array[1..5] of string = ('','','','',' limit 0 ');
    const selectEmpresa: array[1..5] of string = ('','','','',' limit 0 ');
    const selectEndereco: array[1..5] of string = ('','','','',' limit 0 ');
    const selectEntradaCabecalho: array[1..5] of string = ('','','','',' limit 0 ');
    const selectEntradaDuplicado: array[1..5] of string = ('','','','',' limit 0 ');
    const selectEntradaItem: array[1..5] of string = ('','','','',' limit 0 ');
    const selectEntradaItemImposto: array[1..5] of string = ('','','','',' limit 0 ');
    const selectEntradaLocalEntregaRetirada: array[1..5] of string = ('','','','',' limit 0 ');
    const selectEntradaTransportadora: array[1..5] of string = ('','','','',' limit 0 ');
    const selectEntradaTransportadoraReboque: array[1..5] of string = ('','','','',' limit 0 ');
    const selectEstado: array[1..5] of string = ('','','','',' limit 0 ');
    const selectEstoqueContagemCabecalho: array[1..5] of string = ('','','','',' limit 0 ');
    const selectEstoqueContagemDetalhe: array[1..5] of string = ('','','','',' limit 0 ');
    const selectEstoqueCor: array[1..5] of string = ('','','','',' limit 0 ');
    const selectEstoqueGrade: array[1..5] of string = ('','','','',' limit 0 ');
    const selectEstoqueTamanho: array[1..5] of string = ('','','','',' limit 0 ');
    const selectHistoricoMovimento: array[1..5] of string = ('','','','',' limit 0 ');
    const selectIndicadorEconomico: array[1..5] of string = ('','','','',' limit 0 ');
    const selectIndice: array[1..5] of string = ('','','','',' limit 0 ');
    const selectLicitacao: array[1..5] of string = ('','','','',' limit 0 ');
    const selectLicitacaoDocumento: array[1..5] of string = ('','','','',' limit 0 ');
    const selectModelo: array[1..5] of string = ('','','','',' limit 0 ');
    const selectMovimento: array[1..5] of string = ('','','','',' limit 0 ');
    const selectMovimentoCheque: array[1..5] of string = ('','','','',' limit 0 ');
    const selectMunicipio: array[1..5] of string = ('','','','',' limit 0 ');
    const selectNCM: array[1..5] of string = ('','','','',' limit 0 ');
    const selectNFeCabecalho: array[1..5] of string = ('','','','',' limit 0 ');
    const selectNFeCupomFiscalReferenciado: array[1..5] of string = ('','','','',' limit 0 ');
    const selectNFeDeclaracaoImportacao: array[1..5] of string = ('','','','',' limit 0 ');
    const selectNFeDestinatario: array[1..5] of string = ('','','','',' limit 0 ');
    const selectNFeDuplicata: array[1..5] of string = ('','','','',' limit 0 ');
    const selectNFeImportacaoDetalhe: array[1..5] of string = ('','','','',' limit 0 ');
    const selectNFeItem: array[1..5] of string = ('','','','',' limit 0 ');
    const selectNFeItemII: array[1..5] of string = ('','','','',' limit 0 ');
    const selectNFeItemImposto: array[1..5] of string = ('','','','',' limit 0 ');
    const selectNFeLocalEntregaRetirada: array[1..5] of string = ('','','','',' limit 0 ');
    const selectNFeNFReferenciada: array[1..5] of string = ('','','','',' limit 0 ');
    const selectNFeProdutorRuralReferenciada: array[1..5] of string = ('','','','',' limit 0 ');
    const selectNFeReferenciada: array[1..5] of string = ('','','','',' limit 0 ');
    const selectNFeTransportadora: array[1..5] of string = ('','','','',' limit 0 ');
    const selectNFeTransportadoraReboque: array[1..5] of string = ('','','','',' limit 0 ');
    const selectOrcamentoCabecalho: array[1..5] of string = ('','','','',' limit 0 ');
    const selectOrcamentoItem: array[1..5] of string = ('','','','',' limit 0 ');
    const selectPais: array[1..5] of string = ('','','','',' limit 0 ');
    const selectPedidoCabecalho: array[1..5] of string = ('','','','',' limit 0 ');
    const selectPedidoItem: array[1..5] of string = ('','','','',' limit 0 ');
    const selectPessoa: array[1..5] of string = ('','','','',' limit 0 ');
    const selectPessoaCliente: array[1..5] of string = ('','','','',' limit 0 ');
    const selectPessoaColaborador: array[1..5] of string = ('','','','',' limit 0 ');
    const selectPessoaContador: array[1..5] of string = ('','','','',' limit 0 ');
    const selectPessoaFornecedor: array[1..5] of string = ('','','','',' limit 0 ');
    const selectPessoaRepresentante: array[1..5] of string = ('','','','',' limit 0 ');
    const selectPessoaTransportadora: array[1..5] of string = ('','','','',' limit 0 ');
    const selectPessoaVendedor: array[1..5] of string = ('','','','',' limit 0 ');
    const selectPlanoContasFinanceiro: array[1..5] of string = ('','','','',' limit 0 ');
    const selectPlanoContasGerencial: array[1..5] of string = ('','','','',' limit 0 ');
    const selectPortador: array[1..5] of string = ('','','','',' limit 0 ');
    const selectPortadorHistorico: array[1..5] of string = ('','','','',' limit 0 ');
    const selectProduto: array[1..5] of string = ('','','','',' limit 0 ');
    const selectProdutoFornecedor: array[1..5] of string = ('','','','',' limit 0 ');
    const selectProdutoGrupo: array[1..5] of string = ('','','','',' limit 0 ');
    const selectProdutoPromocao: array[1..5] of string = ('','','','',' limit 0 ');
    const selectProdutoSubGrupo: array[1..5] of string = ('','','','',' limit 0 ');
    const selectProdutoTabelaPreco: array[1..5] of string = ('','','','',' limit 0 ');
    const selectProdutoUnidade: array[1..5] of string = ('','','','',' limit 0 ');
    const selectProdutoUnidadeConversao: array[1..5] of string = ('','','','',' limit 0 ');
    const selectRegraFiscal: array[1..5] of string = ('','','','',' limit 0 ');
    const selectRegraFiscalObservacao: array[1..5] of string = ('','','','',' limit 0 ');
    const selectSerie: array[1..5] of string = ('select * ',' from serie ','',' order by idserie ',' limit 0 ');
    const selectSetor: array[1..5] of string = ('','','','',' limit 0 ');
    const selectTelefone: array[1..5] of string = ('','','','',' limit 0 ');
    const selectTipoOperacao: array[1..5] of string = ('','','','',' limit 0 ');
    const selectTipoTelefone: array[1..5] of string = ('','','','',' limit 0 ');
    const selectUnidadeNegocio: array[1..5] of string = ('','','','',' limit 0 ');
  public
    { Public declarations }
    function EchoString(Value: string): string;
    function ReverseString(Value: string): string;

    //Procedures utilizadas pelo Cliente para aplicação de filtros - DJD
    procedure setSQLSerie(filtro: String);
  end;

  var
    arq : TextFile;

implementation

{$R *.dfm}

uses System.StrUtils;

procedure TServerMethods.LOGopen;
var
  dia, mes, ano : Word;
begin
  DecodeDate(now, ano, mes, dia);

  if not DirectoryExists('C:/InsightSoft') then
    ForceDirectories('C:/InsightSoft');

  if not DirectoryExists('C:/InsightSoft/logs') then
    ForceDirectories('C:/InsightSoft/logs');

  if not FileExists('C:/InsightSoft/logs/logServer'+'-'+FormatFloat('00',dia)+'-'+
    FormatFloat('00',mes)+'-'+FormatFloat('0000',ano)+'.txt') then
  begin
    AssignFile(arq,'C:/InsightSoft/logs/logServer'+'-'+FormatFloat('00',dia)+'-'+
      FormatFloat('00',mes)+'-'+FormatFloat('0000',ano)+'.txt');
    Rewrite(arq);
    Writeln(arq);
    CloseFile(arq);
  end;

  AssignFile(arq, 'C:/InsightSoft/logs/logServer'+'-'+FormatFloat('00',dia)+'-'+
    FormatFloat('00',mes)+'-'+FormatFloat('0000',ano)+'.txt');
  Append(arq);
end;

procedure TServerMethods.LOGclose;
begin
  CloseFile(arq);
end;

procedure TServerMethods.LOGadd(msg: String);
begin
  try
    Writeln(arq, DateTimeToStr(now) + ': ' + msg);
  except

  end;
end;

procedure TServerMethods.alteraSQL(Query: TFDQuery; filtro, select, from, where, order: String);
begin
  Query.Close;
  Query.SQL.Clear;
  if filtro <> '*' then
  begin //Tem algo a Filtrar
    if where = '' then
    begin
      Query.SQL.Add(select+from+' where '+filtro+' '+order);
    end
    else
    begin
      Query.SQL.Add(select+from+where+' and '+filtro+' '+order);
    end;
  end
  else
  begin //Todos os dados
    Query.SQL.Add(select+from+where+order);
  end;

  LOGopen;
  LOGadd('SQL de '+Query.Name+' alterada para ['+Trim(Query.SQL.Text)+']');
  LOGclose;
end;

procedure TServerMethods.DSServerModuleCreate(Sender: TObject);
var
  I : Integer;
begin
  //Fazer aqui conforme abaixo

  //qrySerie
  With qrySerie do
  begin
    SQL.Clear;
    for I := 1 to 5 do
      SQL.Add(selectSerie[I]);
  end;
end;

function TServerMethods.EchoString(Value: string): string;
begin
  Result := Value;
end;

function TServerMethods.ReverseString(Value: string): string;
begin
  Result := System.StrUtils.ReverseString(Value);
end;

procedure TServerMethods.setSQLSerie(filtro: String);
begin
  alteraSQL(qrySerie,filtro,selectSerie[1],selectSerie[2],selectSerie[3],selectSerie[4]);
end;

end.

