program DarumaFramework_Delphi_XE5;

uses
  Forms,
  Daruma_Framework_Principal in 'Daruma_Framework_Principal.pas' {FR_DarumaFramework_Principal},
  Daruma_Framework_TA2000_Principal in 'Daruma_Framework_TA2000_Principal.pas' {FR_MenuTA2000_Principal},
  Daruma_Framework_DUAL_Principal in 'Daruma_Framework_DUAL_Principal.pas' {FR_MenuImpressoraDual_Principal},
  Daruma_Framework_DUAL_metodo_iImprimirTexto_DUAL_DarumaFramework in 'Daruma_Framework_DUAL_metodo_iImprimirTexto_DUAL_DarumaFramework.pas' {FR_DUAL_iImprimirTexto_DUAL_DarumaFramework},
  Daruma_Framework_DUAL_metodo_iAutenticarDocumento_DUAL_DarumaFramework in 'Daruma_Framework_DUAL_metodo_iAutenticarDocumento_DUAL_DarumaFramework.pas' {FR_DUAL_iAutenticarDocumento_DUAL_DarumaFramework},
  Daruma_Framework_DUAL_verificacaoLoopingStatus in 'Daruma_Framework_DUAL_verificacaoLoopingStatus.pas' {FR_DUAL_menuTestes_LoopingStatus},
  Daruma_Framework_DUAL_verificacaoLoopingStatusDocumento in 'Daruma_Framework_DUAL_verificacaoLoopingStatusDocumento.pas' {FR_DUAL_menuTestes_LoopingStatusDocumento},
  Daruma_Framework_DUAL_menuExemplo4Formulario in 'Daruma_Framework_DUAL_menuExemplo4Formulario.pas' {FR_DUAL_menuExemplo4_comForumulario},
  Daruma_Framework_MODEM_Principal in 'Daruma_Framework_MODEM_Principal.pas' {FR_MenuMODEM_Principal},
  Daruma_Framework_MODEM_eApagarSms_MODEM_DarumaFramework in 'Daruma_Framework_MODEM_eApagarSms_MODEM_DarumaFramework.pas' {FR_MODEM_eApagarSMS},
  Daruma_Framework_MODEM_rListarSms_MODEM_DarumaFramework in 'Daruma_Framework_MODEM_rListarSms_MODEM_DarumaFramework.pas' {FR_MODEM_rListarSms},
  Daruma_Framework_MODEM_rNivelSinalRecebido_MODEM_DarumaFramework in 'Daruma_Framework_MODEM_rNivelSinalRecebido_MODEM_DarumaFramework.pas' {FR_MODEM_rNivelSinalRecebido},
  Daruma_Framework_MODEM_rReceberSms_MODEM_DarumaFramework in 'Daruma_Framework_MODEM_rReceberSms_MODEM_DarumaFramework.pas' {FR_MODEM_rReceberSms},
  Daruma_Framework_MODEM_rRetornarImei_MODEM_DarumaFramework in 'Daruma_Framework_MODEM_rRetornarImei_MODEM_DarumaFramework.pas' {FR_MODEM_rRetornarImei},
  Daruma_Framework_MODEM_rRetornarOperadora_MODEM_DarumaFramework in 'Daruma_Framework_MODEM_rRetornarOperadora_MODEM_DarumaFramework.pas' {FR_MODEM_rRetornarOperadora},
  Daruma_Framework_MODEM_tEnviarSms_MODEM_DarumaFramework in 'Daruma_Framework_MODEM_tEnviarSms_MODEM_DarumaFramework.pas' {FR_MODEM_tEnviarSMS},
  Daruma_Framework_MODEM_ServicoCSD in 'Daruma_Framework_MODEM_ServicoCSD.pas' {FR_MODEM_ServicoCSD},
  Daruma_Framework_FISCAL_Principal in 'Daruma_Framework_FISCAL_Principal.pas' {FR_MenuImpressoraFiscal_Principal},
  Daruma_Framework_FISCAL_iCFVender_ECF_Daruma in 'Daruma_Framework_FISCAL_iCFVender_ECF_Daruma.pas' {FR_FISCAL_iCFVender_ECF_Daruma},
  Daruma_Framework_FISCAL_iCFVenderResumido_ECF_Daruma in 'Daruma_Framework_FISCAL_iCFVenderResumido_ECF_Daruma.pas' {FR_FISCAL_iCFVenderResumido_ECF_Daruma},
  Daruma_Framework_FISCAL_iCFVenderSemDesc_ECF_Daruma in 'Daruma_Framework_FISCAL_iCFVenderSemDesc_ECF_Daruma.pas' {FR_FISCAL_iCFVenderSemDesc_ECF_Daruma},
  Daruma_Framework_FISCAL_iCFAbrir_ECF_Daruma in 'Daruma_Framework_FISCAL_iCFAbrir_ECF_Daruma.pas' {FR_FISCAL_iCFAbrir_ECF_Daruma},
  Daruma_Framework_FISCAL_rStatusImpressora_ECF_Daruma in 'Daruma_Framework_FISCAL_rStatusImpressora_ECF_Daruma.pas' {FR_FISCAL_rStatusImpressora_ECF_Daruma},
  Daruma_Framework_FISCAL_rRetornarInformacao_ECF_Daruma in 'Daruma_Framework_FISCAL_rRetornarInformacao_ECF_Daruma.pas' {FR_FISCAL_rRetornarInformacao_ECF_Daruma},
  Daruma_Framework_FISCAL_rGerarRelatorio_ECF_Daruma in 'Daruma_Framework_FISCAL_rGerarRelatorio_ECF_Daruma.pas' {FR_FISCAL_rGerarRelatorio},
  Daruma_Framework_FISCAL_rGerarRelatorioOffline_ECF_Daruma in 'Daruma_Framework_FISCAL_rGerarRelatorioOffline_ECF_Daruma.pas' {FR_FISCAL_rGerarRelatorioOffline},
  Daruma_Framework_FISCAL_iCFEfetuarPagamento_ECF_Daruma in 'Daruma_Framework_FISCAL_iCFEfetuarPagamento_ECF_Daruma.pas' {FR_FISCAL_iCFEfetuarPagamento_ECF_Daruma},
  Daruma_Framework_FISCAL_iCNFEfetuarPagamentoFormatado_ECF_Daruma in 'Daruma_Framework_FISCAL_iCNFEfetuarPagamentoFormatado_ECF_Daruma.pas' {FR_FISCAL_iCNFEfetuarPagamentoFormatado_ECF_Daruma},
  Daruma_Framework_FISCAL_iCFEncerrar_ECF_Daruma in 'Daruma_Framework_FISCAL_iCFEncerrar_ECF_Daruma.pas' {FR_FISCAL_iCFEncerrar_ECF_Daruma},
  Daruma_Framework_FISCAL_iCCDAbrir_ECF_Daruma in 'Daruma_Framework_FISCAL_iCCDAbrir_ECF_Daruma.pas' {FR_FISCAL_iCCDAbrir_ECF_Daruma},
  Daruma_Framework_FISCAL_iCCDAbrirSimplificado_ECF_Daruma in 'Daruma_Framework_FISCAL_iCCDAbrirSimplificado_ECF_Daruma.pas' {FR_FISCAL_iCCDAbrirSimplificado_ECF_Daruma},
  Daruma_Framework_FISCAL_iCCDEstornar_ECF_Daruma in 'Daruma_Framework_FISCAL_iCCDEstornar_ECF_Daruma.pas' {FR_FISCAL_iCCDEstornar_ECF_Daruma},
  Daruma_Framework_FISCAL_iCCDImprimirTexto_ECF_Daruma in 'Daruma_Framework_FISCAL_iCCDImprimirTexto_ECF_Daruma.pas' {FR_FISCAL_iCCDImprimirTexto_ECF_Daruma},
  Daruma_Framework_FISCAL_confCadastrarPadrao_ECF_Daruma in 'Daruma_Framework_FISCAL_confCadastrarPadrao_ECF_Daruma.pas' {FR_FISCAL_confCadastrarPadrao_ECF_Daruma},
  Daruma_Framework_FISCAL_eAcionarGuilhotina_ECF_Daruma in 'Daruma_Framework_FISCAL_eAcionarGuilhotina_ECF_Daruma.pas' {FR_FISCAL_eAcionarGuilhotina_ECF_Daruma},
  Daruma_Framework_FISCAL_iMFLer_ECF_Daruma in 'Daruma_Framework_FISCAL_iMFLer_ECF_Daruma.pas' {FR_FISCAL_iMFLer_ECF_Daruma},
  Daruma_Framework_FISCAL_confProgramarAvancoPapel_ECF_Daruma in 'Daruma_Framework_FISCAL_confProgramarAvancoPapel_ECF_Daruma.pas' {FR_FISCAL_confProgramarAvancoPapel_ECF_Daruma},
  Daruma_Framework_FISCAL_confCadastrar_ECF_Daruma in 'Daruma_Framework_FISCAL_confCadastrar_ECF_Daruma.pas' {FR_FISCAL_confCadastrar_ECF_Daruma},
  Daruma_Framework_FISCAL_confCFBPProgramarUF_ECF_Daruma in 'Daruma_Framework_FISCAL_confCFBPProgramarUF_ECF_Daruma.pas' {FR_FISCAL_confCFBPProgramarUF_ECF_Daruma},
  Daruma_Framework_FISCAL_confProgramarIDLoja_ECF_Daruma in 'Daruma_Framework_FISCAL_confProgramarIDLoja_ECF_Daruma.pas' {FR_FISCAL_confProgramarIDLoja_ECF_Daruma},
  Daruma_Framework_FISCAL_confProgramarOperador_ECF_Daruma in 'Daruma_Framework_FISCAL_confProgramarOperador_ECF_Daruma.pas' {FR_FISCAL_confProgramarOperador_ECF_Daruma},
  Daruma_Framework_FISCAL_iCFBPAbrir_ECF_Daruma in 'Daruma_Framework_FISCAL_iCFBPAbrir_ECF_Daruma.pas' {FR_FISCAL_iCFBPAbrir_ECF_Daruma},
  Daruma_Framework_FISCAL_iCFBPVender_ECF_Daruma in 'Daruma_Framework_FISCAL_iCFBPVender_ECF_Daruma.pas' {FR_FISCAL_iCFBPVender_ECF_Daruma},
  Daruma_Framework_FISCAL_iCFCancelarItem_ECF_Daruma in 'Daruma_Framework_FISCAL_iCFCancelarItem_ECF_Daruma.pas' {FR_FISCAL_iCFCancelarItem_ECF_Daruma},
  Daruma_Framework_FISCAL_iCFCancelarItemParcial_ECF_Daruma in 'Daruma_Framework_FISCAL_iCFCancelarItemParcial_ECF_Daruma.pas' {FR_FISCAL_iCFCancelarItemParcial_ECF_Daruma},
  Daruma_Framework_FISCAL_iCFCancelarUltimoItemParcial_ECF_Daruma in 'Daruma_Framework_FISCAL_iCFCancelarUltimoItemParcial_ECF_Daruma.pas' {FR_FISCAL_iCFCancelarUltimoItemParcial_ECF_Daruma},
  Daruma_Framework_FISCAL_iCFEfetuarPagamentoFormatado_ECF_Daruma in 'Daruma_Framework_FISCAL_iCFEfetuarPagamentoFormatado_ECF_Daruma.pas' {FR_FISCAL_iCFEfetuarPagamentoFormatado_ECF_Daruma},
  Daruma_Framework_FISCAL_iCFEncerrarConfigMsg_ECF_Daruma in 'Daruma_Framework_FISCAL_iCFEncerrarConfigMsg_ECF_Daruma.pas' {FR_FISCAL_iCFEncerrarConfigMsg_ECF_Daruma},
  Daruma_Framework_FISCAL_iCFIdentificarConsumidor_ECF_Daruma in 'Daruma_Framework_FISCAL_iCFIdentificarConsumidor_ECF_Daruma.pas' {FR_FISCAL_iCFIdentificarConsumidor_ECF_Daruma},
  Daruma_Framework_FISCAL_iCFLancarAcrescimoItem_ECF_Daruma in 'Daruma_Framework_FISCAL_iCFLancarAcrescimoItem_ECF_Daruma.pas' {FR_FISCAL_iCFLancarAcrescimoItem_ECF_Daruma},
  Daruma_Framework_FISCAL_iCFLancarAcrescimoUltimoItem_ECF_Daruma in 'Daruma_Framework_FISCAL_iCFLancarAcrescimoUltimoItem_ECF_Daruma.pas' {FR_FISCAL_iCFLancarAcrescimoUltimoItem_ECF_Daruma},
  Daruma_Framework_FISCAL_iCFLancarDescontoItem_ECF_Daruma in 'Daruma_Framework_FISCAL_iCFLancarDescontoItem_ECF_Daruma.pas' {FR_FISCAL_iCFLancarDescontoItem_ECF_Daruma},
  Daruma_Framework_FISCAL_iCFLancarDescontoUltimoItem_ECF_Daruma in 'Daruma_Framework_FISCAL_iCFLancarDescontoUltimoItem_ECF_Daruma.pas' {FR_FISCAL_iCFLancarDescontoUltimoItem_ECF_Daruma},
  Daruma_Framework_FISCAL_iCNFAbrir_ECF_Daruma in 'Daruma_Framework_FISCAL_iCNFAbrir_ECF_Daruma.pas' {FR_FISCAL_iCNFAbrir_ECF_Daruma},
  Daruma_Framework_FISCAL_iCNFCancelarAcrescimoItem_ECF_Daruma in 'Daruma_Framework_FISCAL_iCNFCancelarAcrescimoItem_ECF_Daruma.pas' {FR_FISCAL_iCNFCancelarAcrescimoItem_ECF_Daruma},
  Daruma_Framework_FISCAL_iCNFCancelarDescontoItem_ECF_Daruma in 'Daruma_Framework_FISCAL_iCNFCancelarDescontoItem_ECF_Daruma.pas',
  Daruma_Framework_FISCAL_iCNFCancelarItem_ECF_Daruma in 'Daruma_Framework_FISCAL_iCNFCancelarItem_ECF_Daruma.pas' {FR_FISCAL_iCNFCancelarItem_ECF_Daruma},
  Daruma_Framework_FISCAL_iCNFEfetuarPagamento_ECF_Daruma in 'Daruma_Framework_FISCAL_iCNFEfetuarPagamento_ECF_Daruma.pas' {FR_FISCAL_iCNFEfetuarPagamento_ECF_Daruma},
  Daruma_Framework_FISCAL_iCNFEncerrar_ECF_Daruma in 'Daruma_Framework_FISCAL_iCNFEncerrar_ECF_Daruma.pas' {FR_FISCAL_iCNFEncerrar_ECF_Daruma},
  Daruma_Framework_FISCAL_iCNFReceberSemDesc_ECF_Daruma in 'Daruma_Framework_FISCAL_iCNFReceberSemDesc_ECF_Daruma.pas' {FR_FISCAL_iCNFReceberSemDesc_ECF_Daruma},
  Daruma_Framework_FISCAL_iCNFTotalizarComprovante_ECF_Daruma in 'Daruma_Framework_FISCAL_iCNFTotalizarComprovante_ECF_Daruma.pas' {FR_FISCAL_iCNFTotalizarComprovante_ECF_Daruma},
  Daruma_Framework_FISCAL_iMFLerSerial_ECF_Daruma in 'Daruma_Framework_FISCAL_iMFLerSerial_ECF_Daruma.pas' {FR_FISCAL_iMFLerSerial_ECF_Daruma},
  Daruma_Framework_FISCAL_iRGAbrir_ECF_Daruma in 'Daruma_Framework_FISCAL_iRGAbrir_ECF_Daruma.pas' {FR_FISCAL_iRGAbrir_ECF_Daruma},
  Daruma_Framework_FISCAL_iRGAbrirIndice_ECF_Daruma in 'Daruma_Framework_FISCAL_iRGAbrirIndice_ECF_Daruma.pas' {FR_FISCAL_iRGAbrirIndice_ECF_Daruma},
  Daruma_Framework_FISCAL_iRGImprimirTexto_ECF_Daruma in 'Daruma_Framework_FISCAL_iRGImprimirTexto_ECF_Daruma.pas' {FR_FISCAL_iRGImprimirTexto_ECF_Daruma},
  Daruma_Framework_FISCAL_iSangria_ECF_Daruma in 'Daruma_Framework_FISCAL_iSangria_ECF_Daruma.pas' {FR_FISCAL_iSangria_ECF_Daruma},
  Daruma_Framework_FISCAL_iSuprimento_ECF_Daruma in 'Daruma_Framework_FISCAL_iSuprimento_ECF_Daruma.pas' {FR_FISCAL_iSuprimento_ECF_Daruma},
  Daruma_Framework_FISCAL_ParametrizacaoSintegra in 'Daruma_Framework_FISCAL_ParametrizacaoSintegra.pas' {FR_FISCAL_ParametrizacaoSintegra},
  Daruma_Framework_FISCAL_RetornoECF in 'Daruma_Framework_FISCAL_RetornoECF.pas' {FR_FISCAL_RetornoECF},
  Daruma_Framework_FISCAL_rGerarEspelhoMFD_ECF_Daruma in 'Daruma_Framework_FISCAL_rGerarEspelhoMFD_ECF_Daruma.pas' {FR_FISCAL_rGerarEspelhoMFD_ECF_Daruma},
  Daruma_Framework_FISCAL_rLeituraXCustomizada_ECF_Daruma in 'Daruma_Framework_FISCAL_rLeituraXCustomizada_ECF_Daruma.pas' {FR_FISCAL_rLeituraXCustomizada_ECF_Daruma},
  Daruma_Framework_FISCAL_iImprimirCodigoBarras_ECF_Daruma in 'Daruma_Framework_FISCAL_iImprimirCodigoBarras_ECF_Daruma.pas' {FR_FISCAL_iImprimirCodigoBarras_ECF_Daruma},
  Daruma_Framework_FISCAL_rAssinarRSA_ECF_Daruma in 'Daruma_Framework_FISCAL_rAssinarRSA_ECF_Daruma.pas' {FR_FISCAL_AssinarRSA_ECF_Daruma},
  Daruma_Framework_FISCAL_rCalcularMD5_ECF_Daruma in 'Daruma_Framework_FISCAL_rCalcularMD5_ECF_Daruma.pas' {FR_FISCAL_rCalcularMD5_ECF_Daruma},
  Daruma_Framework_FISCAL_rRetornarGTCodificado_ECF_Daruma in 'Daruma_Framework_FISCAL_rRetornarGTCodificado_ECF_Daruma.pas' {FR_FISCAL_rRetornarGTCodificado_ECF_Daruma},
  Daruma_Framework_FISCAL_rVerificarGTCodificado_ECF_Daruma in 'Daruma_Framework_FISCAL_rVerificarGTCodificado_ECF_Daruma.pas' {FR_FISCAL_rVerificarGTCodificado_ECF_Daruma},
  Daruma_Framework_FISCAL_rRetornarNumeroSerieCodificado_ECF_Daruma in 'Daruma_Framework_FISCAL_rRetornarNumeroSerieCodificado_ECF_Daruma.pas' {FR_FISCAL_rRetornarNumeroSerieCodificado_ECF_Daruma},
  Daruma_Framework_FISCAL_rVerificarNumeroSerieCodificado_ECF_Daruma in 'Daruma_Framework_FISCAL_rVerificarNumeroSerieCodificado_ECF_Daruma.pas' {FR_FISCAL_rVerificarNumeroSerieCodificado_ECF_Daruma},
  Daruma_Framework_FISCAL_eDefinirProduto_Daruma in 'Daruma_Framework_FISCAL_eDefinirProduto_Daruma.pas' {FR_FISCAL_eDefinirProduto_Daruma},
  Daruma_Framework_FISCAL_eDefinirModoRegistro_Daruma in 'Daruma_Framework_FISCAL_eDefinirModoRegistro_Daruma.pas' {FR_FISCAL_eDefinirModoRegistro_Daruma},
  Daruma_Framework_FISCAL_TestedeVendadeItensSemPararBuferizando in 'Daruma_Framework_FISCAL_TestedeVendadeItensSemPararBuferizando.pas' {FR_FISCAL_TestedeVendadeItensSemPararBuferizan},
  Daruma_Framework_FISCAL_TesteConsumoMFD in 'Daruma_Framework_FISCAL_TesteConsumoMFD.pas' {FR_FISCAL_Teste_Consumo_MFD},
  Daruma_Framework_FISCAL_MENUFISCAL_LMFC in 'Daruma_Framework_FISCAL_MENUFISCAL_LMFC.pas' {FR_FISCAL_MENUFISCAL_LMFC},
  Daruma_Framework_FISCAL_MENUFISCAL_LMFS in 'Daruma_Framework_FISCAL_MENUFISCAL_LMFS.pas' {FR_FISCAL_MENUFISCAL_LMFS},
  Daruma_Framework_FISCAL_MENUFISCAL_ArqMFD in 'Daruma_Framework_FISCAL_MENUFISCAL_ArqMFD.pas' {FR_FISCAL_MENUFISCAL_ArqMFD},
  Daruma_Framework_FISCAL_MENUFISCAL_Info in 'Daruma_Framework_FISCAL_MENUFISCAL_Info.pas' {FR_FISCAL_MENU_FISCAL_Info},
  Daruma_Framework_FISCAL_iEstornarPagamento_ECF_Daruma in 'Daruma_Framework_FISCAL_iEstornarPagamento_ECF_Daruma.pas' {FR_FISCAL_iCEstornarPagamento_ECF_Daruma},
  Daruma_Framework_FISCAL_eTEF_EsperarArquivo_ECF_Daruma in 'Daruma_Framework_FISCAL_eTEF_EsperarArquivo_ECF_Daruma.pas' {FR_FISCAL_eTEF_EsperarArquivo_ECF_Daruma},
  Daruma_Framework_FISCAL_iTEF_ImprimirResposta_ECF_Daruma in 'Daruma_Framework_FISCAL_iTEF_ImprimirResposta_ECF_Daruma.pas' {FR_FISCAL_iTEF_ImprimirResposta_ECF_Daruma},
  Daruma_Framework_FISCAL_iCFTotalizar in 'Daruma_Framework_FISCAL_iCFTotalizar.pas' {Form1},
  Daruma_Framework_FISCAL_eRSAAssinarArquivo_ECF_Daruma in 'Daruma_Framework_FISCAL_eRSAAssinarArquivo_ECF_Daruma.pas' {FR_FISCAL_eRSAAssinarArquivo},
  Daruma_Framework_FISCAL_iCFTotalizarCupom_ECF_Daruma in 'Daruma_Framework_FISCAL_iCFTotalizarCupom_ECF_Daruma.pas' {FR_FISCAL_iCFTotalizarCupom_ECF_Daruma},
  Daruma_Framework_FISCAL_iCNFReceber_ECF_Daruma in 'Daruma_Framework_FISCAL_iCNFReceber_ECF_Daruma.pas' {FR_FISCAL_iCNFReceber_ECF_Daruma},
  Daruma_Framework_FISCAL_rRetornarInformacaoSeparador_ECF_Daruma in 'Daruma_Framework_FISCAL_rRetornarInformacaoSeparador_ECF_Daruma.pas' {FR_FISCAL_rRetornarInformacaoSeparador_ECF_Daruma},
  Daruma_Framework_DSP_Principal in 'Daruma_Framework_DSP_Principal.pas' {FR_MenuDisplay_Principal},
  Daruma_Framework_FISCAL_rGerarMFD_ECF_Daruma in 'Daruma_Framework_FISCAL_rGerarMFD_ECF_Daruma.pas' {FR_FISCAL_rGerarMFD_ECF_Daruma};




//Daruma_Framework_FISCAL_iTEF_ImprimirRespostaCartao_ECF_Daruma in 'Daruma_Framework_FISCAL_iTEF_ImprimirRespostaCartao_ECF_Daruma.pas' {FR_FISCAL_iTEF_ImprimirRespostaCartao_ECF_Daruma};

// Daruma_Framework_FISCAL_ParametrizacaoSintegra in 'Daruma_Framework_FISCAL_ParametrizacaoSintegra.pas' {FR_FISCAL_ParametrizacaoSintegra};

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TFR_DarumaFramework_Principal, FR_DarumaFramework_Principal);
  Application.CreateForm(TFR_MenuTA2000_Principal, FR_MenuTA2000_Principal);
  Application.CreateForm(TFR_MenuImpressoraDual_Principal, FR_MenuImpressoraDual_Principal);
  Application.CreateForm(TFR_DUAL_iImprimirTexto_DUAL_DarumaFramework, FR_DUAL_iImprimirTexto_DUAL_DarumaFramework);
  Application.CreateForm(TFR_DUAL_iAutenticarDocumento_DUAL_DarumaFramework, FR_DUAL_iAutenticarDocumento_DUAL_DarumaFramework);
  Application.CreateForm(TFR_DUAL_menuTestes_LoopingStatus, FR_DUAL_menuTestes_LoopingStatus);
  Application.CreateForm(TFR_DUAL_menuTestes_LoopingStatusDocumento, FR_DUAL_menuTestes_LoopingStatusDocumento);
  Application.CreateForm(TFR_DUAL_menuExemplo4_comForumulario, FR_DUAL_menuExemplo4_comForumulario);
  Application.CreateForm(TForm1, Form1);
  Application.CreateForm(TFR_FISCAL_iCNFReceber_ECF_Daruma, FR_FISCAL_iCNFReceber_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_rRetornarInformacaoSeparador_ECF_Daruma, FR_FISCAL_rRetornarInformacaoSeparador_ECF_Daruma);
  Application.CreateForm(TFR_MenuDisplay_Principal, FR_MenuDisplay_Principal);
  Application.CreateForm(TFR_FISCAL_rGerarMFD_ECF_Daruma, FR_FISCAL_rGerarMFD_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_rGerarMFD_ECF_Daruma, FR_FISCAL_rGerarMFD_ECF_Daruma);
  //Application.CreateForm(TFR_FISCAL_iTEF_ImprimirRespostaCartao_ECF_Daruma, FR_FISCAL_iTEF_ImprimirRespostaCartao_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_eRSAAssinarArquivo, FR_FISCAL_eRSAAssinarArquivo);
  Application.CreateForm(TFR_FISCAL_iCFTotalizarCupom_ECF_Daruma, FR_FISCAL_iCFTotalizarCupom_ECF_Daruma);
  //Application.CreateForm(TFR_FISCAL_rGerarMFD_ECF_Daruma, FR_FISCAL_rGerarMFD_ECF_Daruma);
  //Application.CreateForm(TFR_DARUMAFRAMEWORK_regRetornaValorChave_DarumaFramework, FR_DARUMAFRAMEWORK_regRetornaValorChave_DarumaFramework);
  Application.CreateForm(TFR_MenuMODEM_Principal, FR_MenuMODEM_Principal);
  Application.CreateForm(TFR_MODEM_eApagarSMS, FR_MODEM_eApagarSMS);
  Application.CreateForm(TFR_MODEM_rListarSms, FR_MODEM_rListarSms);
  Application.CreateForm(TFR_MODEM_rNivelSinalRecebido, FR_MODEM_rNivelSinalRecebido);
  Application.CreateForm(TFR_MODEM_rReceberSms, FR_MODEM_rReceberSms);
  Application.CreateForm(TFR_MODEM_rRetornarImei, FR_MODEM_rRetornarImei);
  Application.CreateForm(TFR_MODEM_rRetornarOperadora, FR_MODEM_rRetornarOperadora);
  Application.CreateForm(TFR_MODEM_tEnviarSMS, FR_MODEM_tEnviarSMS);
  Application.CreateForm(TFR_MODEM_ServicoCSD, FR_MODEM_ServicoCSD);
  Application.CreateForm(TFR_MenuImpressoraFiscal_Principal, FR_MenuImpressoraFiscal_Principal);
  Application.CreateForm(TFR_FISCAL_iCFVender_ECF_Daruma, FR_FISCAL_iCFVender_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCFVenderResumido_ECF_Daruma, FR_FISCAL_iCFVenderResumido_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCFVenderSemDesc_ECF_Daruma, FR_FISCAL_iCFVenderSemDesc_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCFAbrir_ECF_Daruma, FR_FISCAL_iCFAbrir_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_rStatusImpressora_ECF_Daruma, FR_FISCAL_rStatusImpressora_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_rRetornarInformacao_ECF_Daruma, FR_FISCAL_rRetornarInformacao_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_rGerarRelatorio, FR_FISCAL_rGerarRelatorio);
  Application.CreateForm(TFR_FISCAL_rGerarRelatorioOffline, FR_FISCAL_rGerarRelatorioOffline);
  Application.CreateForm(TFR_FISCAL_iCFEfetuarPagamento_ECF_Daruma, FR_FISCAL_iCFEfetuarPagamento_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCNFEfetuarPagamentoFormatado_ECF_Daruma, FR_FISCAL_iCNFEfetuarPagamentoFormatado_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCFEncerrar_ECF_Daruma, FR_FISCAL_iCFEncerrar_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCCDAbrir_ECF_Daruma, FR_FISCAL_iCCDAbrir_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCCDAbrirSimplificado_ECF_Daruma, FR_FISCAL_iCCDAbrirSimplificado_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCCDEstornar_ECF_Daruma, FR_FISCAL_iCCDEstornar_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCCDImprimirTexto_ECF_Daruma, FR_FISCAL_iCCDImprimirTexto_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_confCadastrarPadrao_ECF_Daruma, FR_FISCAL_confCadastrarPadrao_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_eAcionarGuilhotina_ECF_Daruma, FR_FISCAL_eAcionarGuilhotina_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iMFLer_ECF_Daruma, FR_FISCAL_iMFLer_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_confProgramarAvancoPapel_ECF_Daruma, FR_FISCAL_confProgramarAvancoPapel_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_confCadastrar_ECF_Daruma, FR_FISCAL_confCadastrar_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_confCFBPProgramarUF_ECF_Daruma, FR_FISCAL_confCFBPProgramarUF_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_confProgramarOperador_ECF_Daruma, FR_FISCAL_confProgramarOperador_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCFBPAbrir_ECF_Daruma, FR_FISCAL_iCFBPAbrir_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCFBPVender_ECF_Daruma, FR_FISCAL_iCFBPVender_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCFCancelarItem_ECF_Daruma, FR_FISCAL_iCFCancelarItem_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCFCancelarItemParcial_ECF_Daruma, FR_FISCAL_iCFCancelarItemParcial_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCFCancelarUltimoItemParcial_ECF_Daruma, FR_FISCAL_iCFCancelarUltimoItemParcial_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCFEfetuarPagamentoFormatado_ECF_Daruma, FR_FISCAL_iCFEfetuarPagamentoFormatado_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCFEncerrarConfigMsg_ECF_Daruma, FR_FISCAL_iCFEncerrarConfigMsg_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCFIdentificarConsumidor_ECF_Daruma, FR_FISCAL_iCFIdentificarConsumidor_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCFLancarAcrescimoItem_ECF_Daruma, FR_FISCAL_iCFLancarAcrescimoItem_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCFLancarAcrescimoUltimoItem_ECF_Daruma, FR_FISCAL_iCFLancarAcrescimoUltimoItem_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCFLancarDescontoItem_ECF_Daruma, FR_FISCAL_iCFLancarDescontoItem_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCFLancarDescontoUltimoItem_ECF_Daruma, FR_FISCAL_iCFLancarDescontoUltimoItem_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCNFAbrir_ECF_Daruma, FR_FISCAL_iCNFAbrir_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCNFCancelarAcrescimoItem_ECF_Daruma, FR_FISCAL_iCNFCancelarAcrescimoItem_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCNFCancelarItem_ECF_Daruma, FR_FISCAL_iCNFCancelarItem_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCNFEfetuarPagamento_ECF_Daruma, FR_FISCAL_iCNFEfetuarPagamento_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCNFEncerrar_ECF_Daruma, FR_FISCAL_iCNFEncerrar_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCNFReceberSemDesc_ECF_Daruma, FR_FISCAL_iCNFReceberSemDesc_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iCNFTotalizarComprovante_ECF_Daruma, FR_FISCAL_iCNFTotalizarComprovante_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iMFLerSerial_ECF_Daruma, FR_FISCAL_iMFLerSerial_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iRGAbrir_ECF_Daruma, FR_FISCAL_iRGAbrir_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iRGAbrirIndice_ECF_Daruma, FR_FISCAL_iRGAbrirIndice_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iRGImprimirTexto_ECF_Daruma, FR_FISCAL_iRGImprimirTexto_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iSangria_ECF_Daruma, FR_FISCAL_iSangria_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iSuprimento_ECF_Daruma, FR_FISCAL_iSuprimento_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_ParametrizacaoSintegra, FR_FISCAL_ParametrizacaoSintegra);
  Application.CreateForm(TFR_FISCAL_RetornoECF, FR_FISCAL_RetornoECF);
  Application.CreateForm(TFR_FISCAL_rGerarEspelhoMFD_ECF_Daruma, FR_FISCAL_rGerarEspelhoMFD_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_rLeituraXCustomizada_ECF_Daruma, FR_FISCAL_rLeituraXCustomizada_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iImprimirCodigoBarras_ECF_Daruma, FR_FISCAL_iImprimirCodigoBarras_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_AssinarRSA_ECF_Daruma, FR_FISCAL_AssinarRSA_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_rCalcularMD5_ECF_Daruma, FR_FISCAL_rCalcularMD5_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_rRetornarGTCodificado_ECF_Daruma, FR_FISCAL_rRetornarGTCodificado_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_rVerificarGTCodificado_ECF_Daruma, FR_FISCAL_rVerificarGTCodificado_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_rRetornarNumeroSerieCodificado_ECF_Daruma, FR_FISCAL_rRetornarNumeroSerieCodificado_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_rVerificarNumeroSerieCodificado_ECF_Daruma, FR_FISCAL_rVerificarNumeroSerieCodificado_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_eDefinirProduto_Daruma, FR_FISCAL_eDefinirProduto_Daruma);
  Application.CreateForm(TFR_FISCAL_eDefinirModoRegistro_Daruma, FR_FISCAL_eDefinirModoRegistro_Daruma);
  Application.CreateForm(TFR_FISCAL_TestedeVendadeItensSemPararBuferizan, FR_FISCAL_TestedeVendadeItensSemPararBuferizan);
  Application.CreateForm(TFR_FISCAL_Teste_Consumo_MFD, FR_FISCAL_Teste_Consumo_MFD);
  Application.CreateForm(TFR_FISCAL_MENUFISCAL_LMFC, FR_FISCAL_MENUFISCAL_LMFC);
  Application.CreateForm(TFR_FISCAL_MENUFISCAL_LMFS, FR_FISCAL_MENUFISCAL_LMFS);
  Application.CreateForm(TFR_FISCAL_MENUFISCAL_ArqMFD, FR_FISCAL_MENUFISCAL_ArqMFD);
  Application.CreateForm(TFR_FISCAL_MENU_FISCAL_Info, FR_FISCAL_MENU_FISCAL_Info);
  Application.CreateForm(TFR_FISCAL_iEstornarPagamento_ECF_Daruma, FR_FISCAL_iEstornarPagamento_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_eTEF_EsperarArquivo_ECF_Daruma, FR_FISCAL_eTEF_EsperarArquivo_ECF_Daruma);
  Application.CreateForm(TFR_FISCAL_iTEF_ImprimirResposta_ECF_Daruma, FR_FISCAL_iTEF_ImprimirResposta_ECF_Daruma);
 // Application.CreateForm(TFR_FISCAL_iTEF_ImprimirRespostaCartao_ECF_Daruma, FR_FISCAL_iTEF_ImprimirRespostaCartao_ECF_Daruma);
  Application.Run;
end.
